### ISSUE TITLE
[BUG] LPA from the tutorial fails to compile

### ISSUE THREAD

**Issue by michael-golfi** [alibaba/GraphScope#1150]
**Describe the bug**

Running label propagation fails to run on Google Colab

**To Reproduce**

Go to Google Colab and run the following code:

```python
!pip install graphscope

import graphscope
from graphscope.dataset import load_ogbn_mag

sess = graphscope.session(mode="eager", cluster_type='hosts')
g = load_ogbn_mag(sess)
lpa = graphscope.lpa(g)
```

**Expected behavior**

[The tutorial](https://graphscope.io/docs/v0.1.3/analytics_engine.html#built-in-algorithms) has this example

**Environment (please complete the following information):**
 - GraphScope version: 0.9.0
 - OS: Ubuntu (Google Colab)
 - Version 18.04
 - Kubernetes Version N/A, Local mode

**Output**

<details>

```text
2021-12-12 16:00:47,255 [ERROR][rpc:225]: Runstep failed with code: ANALYTICAL_ENGINE_INTERNAL_ERROR, message: Error occurred during preprocessing, The traceback is: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gscoordinator/coordinator.py", line 507, in RunStep
    request.session_id, dag_def, op_results
  File "/usr/local/lib/python3.7/dist-packages/gscoordinator/coordinator.py", line 327, in run_on_analytical_engine
    op, app_sig, app_lib_path = self._maybe_compile_app(op)
  File "/usr/local/lib/python3.7/dist-packages/gscoordinator/coordinator.py", line 547, in _maybe_compile_app
    compile_app, app_sig, op
  File "/usr/local/lib/python3.7/dist-packages/gscoordinator/coordinator.py", line 1082, in _compile_lib_and_distribute
    space, lib_name, op.attr, self._analytical_engine_config
  File "/usr/local/lib/python3.7/dist-packages/gscoordinator/utils.py", line 351, in compile_app
    raise CompilationError(f"Failed to compile app {app_class}")
graphscope.framework.errors.CompilationError: 'Failed to compile app gs::LPAU2I<_GRAPH_TYPE>'

---------------------------------------------------------------------------
CompilationError                          Traceback (most recent call last)
<ipython-input-17-3f3e0863641f> in <module>()
      4 sess = graphscope.session(mode="eager", cluster_type='hosts')
      5 g = load_ogbn_mag(sess)
----> 6 lpa = graphscope.lpa(g)

7 frames
/usr/local/lib/python3.7/dist-packages/graphscope/framework/app.py in wrapper(*args, **kwargs)
    107                 )
    108             else:
--> 109                 return not_compatible_for_func(*args, **kwargs)
    110 
    111         return wrapper

/usr/local/lib/python3.7/dist-packages/graphscope/analytical/app/lpa.py in lpa(graph, max_round)
     48     """
     49     max_round = int(max_round)
---> 50     return AppAssets(algo="lpau2i", context="labeled_vertex_property")(graph, max_round)

/usr/local/lib/python3.7/dist-packages/graphscope/framework/app.py in __call__(self, graph, *args, **kwargs)
    273     def __call__(self, graph, *args, **kwargs):
    274         """Instantiate an App and do queries over it."""
--> 275         app_ = graph.session._wrapper(AppDAGNode(graph, self))
    276         return app_(*args, **kwargs)
    277 

/usr/local/lib/python3.7/dist-packages/graphscope/client/session.py in _wrapper(self, dag_node)
    923     def _wrapper(self, dag_node):
    924         if self.eager():
--> 925             return self.run(dag_node)
    926         else:
    927             return dag_node

/usr/local/lib/python3.7/dist-packages/graphscope/client/session.py in run(self, fetches, debug)
    952         fetch_handler = _FetchHandler(self.dag, fetches)
    953         try:
--> 954             response = self._grpc_client.run(fetch_handler.targets)
    955         except FatalError:
    956             self.close()

/usr/local/lib/python3.7/dist-packages/graphscope/client/rpc.py in run(self, dag_def)
    143 
    144     def run(self, dag_def):
--> 145         return self._run_step_impl(dag_def)
    146 
    147     def fetch_logs(self):

/usr/local/lib/python3.7/dist-packages/graphscope/client/rpc.py in with_grpc_catch(*args, **kwargs)
     44     def with_grpc_catch(*args, **kwargs):
     45         try:
---> 46             return fn(*args, **kwargs)
     47         except grpc.RpcError as exc:
     48             if grpc.StatusCode.INTERNAL == exc.code():

/usr/local/lib/python3.7/dist-packages/graphscope/client/rpc.py in _run_step_impl(self, dag_def)
    226             )
    227             if response.full_exception:
--> 228                 raise pickle.loads(response.full_exception)
    229         return response

CompilationError: "'Failed to compile app gs::LPAU2I<_GRAPH_TYPE>'"
```

</details>

**Additional context**

I tried following another issue's install and ran the following GCC install

```bash
apt-get install software-properties-common

add-apt-repository ppa:ubuntu-toolchain-r/test
apt-get update
apt-get install gcc-7 g++-7
gcc-7 --version

update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
update-alternatives --config gcc

gcc -v
```
GCC version is `v7.5.0`

**Comment by lidongze0629** [comment]
Also, the [LPA algorithm](https://github.com/alibaba/GraphScope/blob/main/analytical_engine/apps/lpa/lpa_u2i_context.h#L43) in our implementation has strong constraints on the number of labels of vertices(=2) and edges(=1), which not described in our [document](https://graphscope.io/docs/analytics_engine.html#built-in-algorithms).

Maybe we can implement a general LPA or update our document.

**Comment by lidongze0629** [comment]
Alternative, you can try [cdlp](https://graphscope.io/docs/reference/app.html#graphscope.cdlp) on a project graph.

```python
import graphscope
from graphscope.dataset import load_ogbn_mag

graphscope.set_option(show_log=True)
sess = graphscope.session(mode="eager", cluster_type='hosts')

# load a property graph
g = load_ogbn_mag(sess)

# project to simple graph
pg = g.project(vertices={"paper": []}, edges={"cites": []})

# run cdlp
r = graphscope.cdlp(pg, max_round=10)
sess.close()
```

**Comment by michael-golfi** [comment]
Thanks @lidongze0629, I wasn't sure if there was a difference between cdlp and lpa. It sounded like cdlp was just a rename of lpa.

**Comment by siyuan0322** [comment]
> I wasn't sure if there was a difference between cdlp and lpa. It sounded like cdlp was just a rename of lpa.

Yes indeed this is confusing for users as the difference of implementation is not reflected on name. We will open an issue to track the enhancement of apps.
