### ISSUE TITLE
[BUG] LPA failed to be compiled on centos 7

### ISSUE THREAD

**Issue by w279805299** [alibaba/GraphScope#1206]
**Describe the bug**
Failed to compile graph gs::ArrowProjectedFragment<int64_t,uint64_t,std::string,std::string> on platform system: Linux
machine: x86_64
platform: Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
uname: uname_result(system='Linux', node='iZuf66r5u8vbc4uzj2wd2hZ', release='3.10.0-957.21.3.el7.x86_64', version='#1 SMP Tue Jun 18 16:35:19 UTC 2019', machine='x86_64', processor='x86_64')
kernel_ver: #1 SMP Tue Jun 18 16:35:19 UTC 2019
mac_ver: ('', ('', '', ''), '')
gcc_ver: b'gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)\nCopyright (C) 2017 Free Software Foundation, Inc.\nThis is free software; see the source for copying conditions.  There is NO\nwarranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n\n'
python_ver: 3.6.8

**To Reproduce**
run follow code:
from graphscope import *
sub_graph2 = graph.project(vertices={"person": ["creationDate"]}, edges={"knows": ["creationDate"]})
ret = lpa(sub_graph2)

**Screenshots**
![image](https://user-images.githubusercontent.com/1842121/146942720-735d5665-ca81-4613-92d0-c1ec2426b47c.png)

**Environment (please complete the following information):**
 - GraphScope version:  0.9.1
 - OS: CentOS Linux release 7.6.1810 (Core) 
 - local

**Additional context**
Just For test.

**Comment by acezen** [comment]
hi, @w279805299, can you run `graphscope.set_option(show_log=True)` after import graphscope and try to run the lpa again to show more log ?

**Comment by w279805299** [comment]
@acezen 
``
import graphscope
graphscope.set_option(show_log=True) # enable logging
from graphscope.framework.loader import Loader
# graph = graphscope.g()
sess = graphscope.session(cluster_type="hosts")
graph = sess.g(oid_type="int64_t", directed=True, generate_eid=True)

graph = graph.add_vertices(
    Loader("${HOME}/.graphscope/datasets/ldbc_sample/person_0_0.csv", delimiter="|"),
    label="person",
)
graph = graph.add_vertices(
    Loader("${HOME}/.graphscope/datasets/ldbc_sample/comment_0_0.csv", delimiter="|"),
    label="comment",
)
graph = graph.add_vertices(
    Loader("${HOME}/.graphscope/datasets/ldbc_sample/post_0_0.csv", delimiter="|"),
    label="post",
)

graph = graph.add_edges(
    Loader(
        "${HOME}/.graphscope/datasets/ldbc_sample/person_knows_person_0_0.csv",
        delimiter="|",
    ),
    label="knows",
    src_label="person",
    dst_label="person",
)
graph = graph.add_edges(
    Loader(
        "${HOME}/.graphscope/datasets/ldbc_sample/person_likes_comment_0_0.csv",
        delimiter="|",
    ),
    label="likes",
    src_label="person",
    dst_label="comment",
)


from graphscope import *
sub_graph2 = graph.project(vertices={"person": ["creationDate"]}, edges={"knows": ["creationDate"]})
ret = lpa(sub_graph2)


2021-12-21 21:28:25,004 [INFO][session:659]: Initializing graphscope session with parameters: {'addr': None, 'mode': 'eager', 'cluster_type': 'hosts', 'num_workers': 2, 'preemptive': True, 'k8s_namespace': None, 'k8s_service_type': 'NodePort', 'k8s_gs_image': 'registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.9.1', 'k8s_etcd_image': 'quay.io/coreos/etcd:v3.4.13', 'k8s_image_pull_policy': 'IfNotPresent', 'k8s_image_pull_secrets': [], 'k8s_coordinator_cpu': 1.5, 'k8s_coordinator_mem': '2Gi', 'k8s_etcd_num_pods': 1, 'k8s_etcd_cpu': 1.0, 'k8s_etcd_mem': '512Mi', 'k8s_vineyard_daemonset': 'none', 'k8s_vineyard_cpu': 0.2, 'k8s_vineyard_mem': '512Mi', 'vineyard_shared_mem': '4Gi', 'k8s_engine_cpu': 0.2, 'k8s_engine_mem': '1Gi', 'k8s_mars_worker_cpu': 0.2, 'k8s_mars_worker_mem': '512Mi', 'k8s_mars_scheduler_cpu': 0.2, 'k8s_mars_scheduler_mem': '512Mi', 'with_mars': False, 'reconnect': False, 'k8s_volumes': {}, 'k8s_waiting_for_delete': False, 'timeout_seconds': 600, 'dangling_timeout_seconds': 600, 'mount_dataset': None, 'k8s_dataset_image': 'registry.cn-hongkong.aliyuncs.com/graphscope/dataset:0.9.1', 'hosts': ['localhost'], 'port': None, 'vineyard_socket': '', 'k8s_client_config': {}}
2021-12-21 21:28:25,014 [INFO][cluster:113]: Initializing coordinator with command: /root/miniconda3/envs/python3/bin/python -m gscoordinator --num_workers 2 --hosts localhost --log_level INFO --timeout_seconds 600 --port 64860 --cluster_type hosts --instance_id zzpnzd --vineyard_shared_mem 4Gi
2021-12-21 21:28:25,042 [INFO][cluster:167]: Coordinator service started successful, connecting to service...
2021-12-21 21:28:35,125 [INFO][rpc:115]: GraphScope coordinator service connected.
2021-12-21 21:28:26,544 [INFO][launcher:335]: Launch etcd with command: /root/miniconda3/envs/python3/bin/etcd --data-dir /tmp/gs/zzpnzd --listen-peer-urls http://0.0.0.0:59862 --listen-client-urls http://0.0.0.0:36671 --advertise-client-urls http://127.0.0.1:36671 --initial-cluster default=http://127.0.0.1:59862 --initial-advertise-peer-urls http://127.0.0.1:598622021-12-21 21:28:26,555 [INFO][launcher:351]: Server is initializing etcd.2021-12-21 21:28:27,574 [INFO][launcher:364]: Etcd is ready, endpoint is localhost:366712021-12-21 21:28:27,575 [INFO][launcher:439]: Launch vineyardd with command: /root/miniconda3/envs/python3/bin/python -m vineyard --socket /tmp/vineyard.sock.1640093307.574713 --size 4Gi -etcd_endpoint http://localhost:36671 -etcd_prefix vineyard.gsa.1640093307.5747132021-12-21 21:28:27,582 [INFO][launcher:455]: Server is initializing vineyardd.I20211221 21:28:28.616561 27038 vineyardd.cc:91] Hello vineyard v0.3.12!I20211221 21:28:28.619112 27038 meta_service.h:134] meta service is starting ...I20211221 21:28:28.626247 27038 etcd_meta_service.cc:266] start background etcd watch, since 1I20211221 21:28:28.633977 27038 meta_service.h:403] Decide to set rank as 0I20211221 21:28:28.633998 27038 meta_service.h:770] Instance join: 0I20211221 21:28:28.636056 27038 ipc_server.cc:51] Vineyard will listen on "/tmp/vineyard.sock.1640093307.574713" for IPCI20211221 21:28:28.636082 27038 rpc_server.cc:52] Vineyard will listen on 0.0.0.0:9600 for RPCI20211221 21:28:28.636096 27038 meta_service.h:770] Instance join: 02021-12-21 21:28:29,593 [INFO][launcher:471]: Vineyardd is ready, ipc socket is /tmp/vineyard.sock.1640093307.5747132021-12-21 21:28:29,668 [INFO][launcher:510]: Launch analytical engine with command: /root/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope.runtime/openmpi/bin/mpirun --allow-run-as-root -n 2 -host localhost:2.0 /root/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope.runtime/bin/grape_engine --host 0.0.0.0 --port 52391 --vineyard_shared_mem 4Gi -v 1 --vineyard_socket /tmp/vineyard.sock.1640093307.5747132021-12-21 21:28:29,677 [INFO][launcher:526]: Server is initializing analytical engine.I1221 21:28:29.000000 27103 /work/analytical_engine/core/grape_instance.cc:55] Workers of grape-engine initialized.I1221 21:28:30.000000 27110 /work/analytical_engine/core/server/analytical_server.cc:36] Analytical server is listening on 0.0.0.0:523912021-12-21 21:28:30,702 [INFO][launcher:545]: Analytical engine is ready, endpoint is localhost:523912021-12-21 21:28:30,766 [INFO][launcher:395]: Server is initializing zetcd.2021-12-21 21:28:31,787 [INFO][launcher:407]: ZEtcd is ready, endpoint is localhost:621322021-12-21 21:28:31,843 [INFO][coordinator:1395]: Coordinator server listen at 0.0.0.0:64860I1221 21:28:55.000000 27109 /work/analytical_engine/core/grape_instance.cc:1000] Registering Graph, graph type: ARROW_PROPERTY, Type sigature: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521, lib path: /root/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope.runtime/precompiled/builtin/e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521/libe33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521.soI1221 21:28:55.000000 27111 /work/analytical_engine/core/grape_instance.cc:1000] Registering Graph, graph type: ARROW_PROPERTY, Type sigature: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521, lib path: /root/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope.runtime/precompiled/builtin/e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521/libe33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521.soI1221 21:28:55.000000 27111 /work/analytical_engine/core/grape_instance.cc:122] Loading graph, graph name: graph_7JncCHry, graph type: ArrowFragment, type sig: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521I1221 21:28:55.000000 27109 /work/analytical_engine/core/grape_instance.cc:122] Loading graph, graph name: graph_7JncCHry, graph type: ArrowFragment, type sig: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521
Loading empty graph:   0%|          | 0/10 [00:00<?, ?it/s]
Loading empty graph: 100%|██████████| 10/10 [00:00<00:00, 113.51it/s]



Loading vertex labeled person:   0%|          | 0/10 [00:00<?, ?it/s]
Loading vertex labeled person: 100%|██████████| 10/10 [00:00<00:00, 30.42it/s]
Loading vertex labeled person: 100%|██████████| 10/10 [00:00<00:00, 30.39it/s]

Loading vertex labeled comment:   0%|          | 0/10 [00:00<?, ?it/s]
Loading vertex labeled comment:  60%|██████    | 6/10 [00:00<00:00,  7.18it/s]
Loading vertex labeled comment: 100%|██████████| 10/10 [00:01<00:00,  9.42it/s]
Loading vertex labeled comment: 100%|██████████| 10/10 [00:01<00:00,  8.92it/s]

Loading vertex labeled post:   0%|          | 0/10 [00:00<?, ?it/s]
Loading vertex labeled post:  60%|██████    | 6/10 [00:00<00:00, 26.78it/s]
Loading vertex labeled post: 100%|██████████| 10/10 [00:00<00:00, 19.67it/s]
Loading vertex labeled post: 100%|██████████| 10/10 [00:00<00:00, 20.64it/s]

Loading edge labeled knows:   0%|          | 0/10 [00:00<?, ?it/s]
Loading edge labeled knows:  80%|████████  | 8/10 [00:00<00:00, 50.74it/s]
Loading edge labeled knows: 100%|██████████| 10/10 [00:00<00:00, 18.72it/s]

Loading edge labeled likes:   0%|          | 0/10 [00:00<?, ?it/s]
Loading edge labeled likes:  60%|██████    | 6/10 [00:00<00:00, 48.90it/s]
Loading edge labeled likes: 100%|██████████| 10/10 [00:02<00:00,  4.01it/s]
oid_type: 5
vid_type: 17
type: VERTEX
Label: person
Properties: Property(0, firstName), Property(1, lastName), Property(2, gender), Property(3, birthday), Property(4, creationDate), Property(5, locationIP), Property(6, browserUsed), Property(7, id)

type: VERTEX
Label: comment
Properties: Property(0, creationDate), Property(1, locationIP), Property(2, browserUsed), Property(3, content), Property(4, length), Property(5, id)

type: VERTEX
Label: post
Properties: Property(0, imageFile), Property(1, creationDate), Property(2, locationIP), Property(3, browserUsed), Property(4, language), Property(5, content), Property(6, length), Property(7, id)

type: EDGE
Label: knows
Properties: Property(0, eid), Property(1, creationDate)
Relations: [Relation(source='person', destination='person')]
type: EDGE
Label: likes
Properties: Property(0, eid), Property(1, creationDate)
Relations: [Relation(source='person', destination='comment')]


2021-12-21 22:02:33,224 [ERROR][rpc:224]: Runstep failed with code: ANALYTICAL_ENGINE_INTERNAL_ERROR, message: Error occurred during preprocessing, The traceback is: Traceback (most recent call last):
  File "/root/miniconda3/envs/python3/lib/python3.6/site-packages/gscoordinator/coordinator.py", line 509, in RunStep
    request.session_id, dag_def, op_results
  File "/root/miniconda3/envs/python3/lib/python3.6/site-packages/gscoordinator/coordinator.py", line 327, in run_on_analytical_engine
    op, app_sig, app_lib_path = self._maybe_compile_app(op)
  File "/root/miniconda3/envs/python3/lib/python3.6/site-packages/gscoordinator/coordinator.py", line 549, in _maybe_compile_app
    compile_app, app_sig, op
  File "/root/miniconda3/envs/python3/lib/python3.6/site-packages/gscoordinator/coordinator.py", line 1077, in _compile_lib_and_distribute
    space, lib_name, op.attr, self._analytical_engine_config
  File "/root/miniconda3/envs/python3/lib/python3.6/site-packages/gscoordinator/utils.py", line 360, in compile_app
    f"Failed to compile app {app_class} on platform {get_platform_info()}"
graphscope.framework.errors.CompilationError: Failed to compile app gs::LPAU2I<_GRAPH_TYPE> on platform system: Linux
machine: x86_64
platform: Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
uname: uname_result(system='Linux', node='iZuf66r5u8vbc4uzj2wd2hZ', release='3.10.0-957.21.3.el7.x86_64', version='#1 SMP Tue Jun 18 16:35:19 UTC 2019', machine='x86_64', processor='x86_64')
kernel_ver: #1 SMP Tue Jun 18 16:35:19 UTC 2019
mac_ver: ('', ('', '', ''), '')
gcc_ver: b'gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)\nCopyright (C) 2017 Free Software Foundation, Inc.\nThis is free software; see the source for copying conditions.  There is NO\nwarranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n\n'
python_ver: 3.6.8


---------------------------------------------------------------------------
CompilationError                          Traceback (most recent call last)
<ipython-input-8-bdb62309ad89> in <module>
      2 sub_graph2 = graph.project(vertices={"person": ["creationDate"]}, edges={"knows": ["creationDate"]})
      3 
----> 4 ret = lpa(sub_graph2)

~/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope/framework/app.py in wrapper(*args, **kwargs)
    110                 )
    111             else:
--> 112                 return not_compatible_for_func(*args, **kwargs)
    113 
    114         return wrapper

~/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope/analytical/app/lpa.py in lpa(graph, max_round)
     48     """
     49     max_round = int(max_round)
---> 50     return AppAssets(algo="lpau2i", context="labeled_vertex_property")(graph, max_round)

~/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope/framework/app.py in __call__(self, graph, *args, **kwargs)
    281     def __call__(self, graph, *args, **kwargs):
    282         """Instantiate an App and do queries over it."""
--> 283         app_ = graph.session._wrapper(AppDAGNode(graph, self))
    284         return app_(*args, **kwargs)
    285 

~/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope/client/session.py in _wrapper(self, dag_node)
    923     def _wrapper(self, dag_node):
    924         if self.eager():
--> 925             return self.run(dag_node)
    926         return dag_node
    927 

~/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope/client/session.py in run(self, fetches, debug)
    951         fetch_handler = _FetchHandler(self.dag, fetches)
    952         try:
--> 953             response = self._grpc_client.run(fetch_handler.targets)
    954         except FatalError:
    955             self.close()

~/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope/client/rpc.py in run(self, dag_def)
    142 
    143     def run(self, dag_def):
--> 144         return self._run_step_impl(dag_def)
    145 
    146     def fetch_logs(self):

~/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope/client/rpc.py in with_grpc_catch(*args, **kwargs)
     43     def with_grpc_catch(*args, **kwargs):
     44         try:
---> 45             return fn(*args, **kwargs)
     46         except grpc.RpcError as exc:
     47             if grpc.StatusCode.INTERNAL == exc.code():

~/miniconda3/envs/python3/lib/python3.6/site-packages/graphscope/client/rpc.py in _run_step_impl(self, dag_def)
    225             )
    226             if response.full_exception:
--> 227                 raise pickle.loads(response.full_exception)
    228         return response

CompilationError: Failed to compile app gs::LPAU2I<_GRAPH_TYPE> on platform system: Linux
machine: x86_64
platform: Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
uname: uname_result(system='Linux', node='iZuf66r5u8vbc4uzj2wd2hZ', release='3.10.0-957.21.3.el7.x86_64', version='#1 SMP Tue Jun 18 16:35:19 UTC 2019', machine='x86_64', processor='x86_64')
kernel_ver: #1 SMP Tue Jun 18 16:35:19 UTC 2019
mac_ver: ('', ('', '', ''), '')
gcc_ver: b'gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)\nCopyright (C) 2017 Free Software Foundation, Inc.\nThis is free software; see the source for copying conditions.  There is NO\nwarranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n\n'
python_ver: 3.6.8

**Comment by lidongze0629** [comment]
@w279805299  Now, Default [LPA algorithm](https://github.com/alibaba/GraphScope/blob/main/analytical_engine/apps/lpa/lpa_u2i_context.h#L43) in our implementation has strong constraints on the number of labels of vertices(=2) and edges(=1), which not described in our [document](https://graphscope.io/docs/analytics_engine.html#built-in-algorithms). Alternatively, you can try [cdlp](https://graphscope.io/docs/reference/app.html#graphscope.cdlp) on a project graph. 

```python
import graphscope
from graphscope.dataset import load_ogbn_mag

graphscope.set_option(show_log=True)
sess = graphscope.session(mode="eager", cluster_type='hosts')

# load a property graph
g = load_ogbn_mag(sess)

# project to simple graph
pg = g.project(vertices={"paper": []}, edges={"cites": []})

# run cdlp
r = graphscope.cdlp(pg, max_round=10)
sess.close()
```

**Comment by yecol** [comment]
@lidongze0629 Could you update the answer with latest status?

**Comment by lidongze0629** [comment]
After the latest release v0.10.0, there are two version implementations of LPA algorithm: 1) lpa and 2) lpa_u2i.

`graphscope.lpa`:  The classic [implementation](https://en.wikipedia.org/wiki/Label_propagation_algorithm).
`graphscope.lpa_u2i`: A customized version for running on a **user-item** graph, which has strong constraints on the number of labels of vertices(=2) and edges(=1).

Here is an example to try `lpa` with built-in dataset.

```
import graphscope
from graphscope.dataset import load_ogbn_mag

graphscope.set_option(show_log=True)
sess = graphscope.session(mode="eager", cluster_type='hosts')

# load a property graph
g = load_ogbn_mag(sess)

# project to simple graph
pg = g.project(vertices={"paper": []}, edges={"cites": []})

# run cdlp
r = graphscope.lpa(pg, max_round=10)
sess.close()
```
