### ISSUE TITLE
[BUG] Error message when k8s doesn't have enough resources

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#1351]
**Describe the bug**

The error message looks bad, as the line `0/2 nodes are available ....` is not very obvious in the exception message, I'm wondering if we could do better to delivery useful error message more explicitly to users?

Be a little hacky should be ok there.

```python
2022-03-03 18:30:59,408 [INFO][session:659]: Initializing graphscope session with parameters: {'addr': None, 'mode': 'eager', 'cluster_type': 'k8s', 'num_workers': 2, 'preemptive': False, 'k8s_namespace': None, 'k8s_service_type': 'NodePort', 'k8s_gs_image': 'registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.10.1', 'k8s_etcd_image': 'quay.io/coreos/etcd:v3.4.13', 'k8s_image_pull_policy': 'IfNotPresent', 'k8s_image_pull_secrets': [], 'k8s_coordinator_cpu': 1.5, 'k8s_coordinator_mem': '2Gi', 'k8s_etcd_num_pods': 1, 'k8s_etcd_cpu': 1.0, 'k8s_etcd_mem': '512Mi', 'k8s_vineyard_daemonset': 'none', 'k8s_vineyard_cpu': 8, 'k8s_vineyard_mem': '2Gi', 'vineyard_shared_mem': '512Gi', 'k8s_engine_cpu': 32, 'k8s_engine_mem': '512Gi', 'k8s_mars_worker_cpu': 0.2, 'k8s_mars_worker_mem': '4Mi', 'k8s_mars_scheduler_cpu': 0.2, 'k8s_mars_scheduler_mem': '2Mi', 'with_mars': False, 'reconnect': False, 'k8s_volumes': {}, 'k8s_waiting_for_delete': False, 'timeout_seconds': 600, 'dangling_timeout_seconds': 600, 'mount_dataset': None, 'k8s_dataset_image': 'registry.cn-hongkong.aliyuncs.com/graphscope/dataset:0.10.1', 'k8s_client_config': {}}
2022-03-03 18:30:59,493 [INFO][cluster:302]: Launching coordinator...
2022-03-03 18:31:02,619 [INFO][utils:164]: coordinator-tcvlrq-597f6cc7cc-jp8kv: 0/2 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.
Traceback (most recent call last):
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 566, in start
    self._waiting_for_services_ready()
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 497, in _waiting_for_services_ready
    timeout_seconds=self._saved_locals["timeout_seconds"],
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/utils.py", line 119, in wait_for_deployment_complete
    raise TimeoutError("Waiting timeout for deployment {}".format(name))
TimeoutError: Waiting timeout for deployment coordinator-tcvlrq

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    sess = gs.session(cluster_type="k8s",k8s_engine_mem='512Gi',k8s_engine_cpu=32,vineyard_shared_mem='512Gi',k8s_vineyard_cpu = 8,k8s_vineyard_mem = "2Gi",num_workers=2,preemptive=False)
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/client/utils.py", line 188, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/client/session.py", line 691, in __init__
    self._connect()
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/client/session.py", line 1013, in _connect
    self._launcher.start()
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 578, in start
    ) from e
graphscope.framework.errors.K8sError: Error when launching Coordinator on kubernetes cluster
```

**Comment by lidongze0629** [comment]
The message `0/2 nodes are available:  xxx` is produced by the Kubernetes event mechanism, which is not an error message. The detail why nodes are unavailable is also described:

> `0/2 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.`

So all we do now is just watch and display, and wait for Pod ready or raise exception after a timeout. Is there any expected error message more explicitly to users ?

**Comment by sighingnow** [comment]
Could we have something like

```
raceback (most recent call last):
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 566, in start
    self._waiting_for_services_ready()
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 497, in _waiting_for_services_ready
    timeout_seconds=self._saved_locals["timeout_seconds"],
  File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/utils.py", line 119, in wait_for_deployment_complete
    raise TimeoutError(".....")
TimeoutError: 0/2 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.
```

**Comment by lidongze0629** [comment]
> Could we have something like
> 
> ```
> raceback (most recent call last):
>   File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 566, in start
>     self._waiting_for_services_ready()
>   File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 497, in _waiting_for_services_ready
>     timeout_seconds=self._saved_locals["timeout_seconds"],
>   File "/home/huangz/python3.7/lib/python3.7/site-packages/graphscope/deploy/kubernetes/utils.py", line 119, in wait_for_deployment_complete
>     raise TimeoutError(".....")
> TimeoutError: 0/2 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.
> ```

Thanks for the suggestion, It looks great and I will do it ASAP.

**Comment by yecol** [comment]
in addition, https://pypi.org/project/pretty-errors/ may also enhance the error displaying.

**Comment by sighingnow** [comment]
Close as won't fix after discussion with @lidongze0629.
