### ISSUE TITLE
graphscope.framework.errors.InteractiveEngineInternalError: Create interactive instance failed.

### ISSUE THREAD

**Issue by caoxiang93** [alibaba/GraphScope#1574]
2022-05-16 16:48:28,480 [ERROR][rpc:188]: Runstep failed with code: INTERACTIVE_ENGINE_INTERNAL_ERROR, message: Error occurred during preprocessing, The traceback is: Traceback (most recent call last):
  File "/usr/local/python/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 858, in _create_interactive_instance
    if check_gremlin_server_ready(maxgraph_endpoint):
  File "/usr/local/python/lib/python3.8/site-packages/gscoordinator/utils.py", line 1933, in check_gremlin_server_ready
    raise TimeoutError(f"Gremlin check query failed: {error_message}")
TimeoutError: Gremlin check query failed: ws:///gremlin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 624, in _RunStep
    head, bodies = self.run_on_interactive_engine(dag)
  File "/usr/local/python/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 514, in run_on_interactive_engine
    op_result = self._create_interactive_instance(op)
  File "/usr/local/python/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 884, in _create_interactive_instance
    raise RuntimeError("Create interactive instance failed.") from e
RuntimeError: Create interactive instance failed.

Traceback (most recent call last):
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/session.py", line 1154, in gremlin
    _wrapper = self._wrapper(
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/session.py", line 936, in _wrapper
    return self.run(dag_node)
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/session.py", line 964, in run
    response = self._grpc_client.run(fetch_handler.targets)
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/rpc.py", line 102, in run
    return self._run_step_impl(runstep_requests)
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/utils.py", line 155, in with_grpc_catch
    return fn(*args, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/rpc.py", line 194, in _run_step_impl
    raise pickle.loads(response.full_exception)
RuntimeError: Create interactive instance failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 43, in <module>
    interactive = graphscope.gremlin(graph)
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/session.py", line 1533, in gremlin
    return get_default_session().gremlin(graph, engine_params)
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/utils.py", line 357, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/graphscope/client/session.py", line 1161, in gremlin
    raise InteractiveEngineInternalError(str(e)) from e
graphscope.framework.errors.InteractiveEngineInternalError: Create interactive instance failed.

**Comment by caoxiang93** [comment]
用root跑是可以的，用普通用户跑就一直报上面的问题

**Comment by lidongze0629** [comment]
@caoxiang93 很有可能是写日志的权限原因导致的，本地拉起方式下，日志默认会写到 `/var/log/graphscope` 下，如果没有权限，则尝试写到  `${HOME}/.local/log/graphscope` 下，你可以检查下这两个路径，大致对应 GIE 的日志结构如下:

```
...
-rw-rw-r-- 1 graphscope graphscope  executor.log
-rw-rw-r-- 1 graphscope graphscope  maxgraph-coordinator.log
-rw-rw-r-- 1 graphscope graphscope  maxgraph-frontend.log
```
如果正常生成了日志，还是有 `Create interactive instance failed` 的错误，则可以将日志内的报错信息贴出来哈

**Comment by caoxiang93** [comment]
![image](https://user-images.githubusercontent.com/34156723/168725073-34753115-d3a9-4acc-8093-2e88eddbea42.png)
maxgraph-executor.err如下
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0517 11:34:39.790513 10096 htap_ds_impl.cc:35] Initialize vineyard client
I0517 11:34:39.824153 10096 htap_ds_impl.cc:39] Get vineyard object ok: 0x55f6c3272190
I0517 11:34:39.824172 10096 htap_ds_impl.cc:43] FragGroup: total frag num = 1, vertex label num = 4, edge label num = 4
I0517 11:34:39.824419 10096 htap_ds_impl.cc:82] fid = 0, instance_id = 0, location = 0
I0517 11:34:39.871021 10096 htap_ds_impl.cc:97] begin get vertex map: 12811363887782892
I0517 11:34:39.874637 10096 htap_ds_impl.cc:133] finish get graph handle: 12811367659796688, handle = 0x55f6c30b4a10

**Comment by lidongze0629** [comment]
`executor.log` 看样子没问题，`maxgraph-coordinator.log` 和 `maxgraph-coordinator.log` 的日志可以贴一下嘛

**Comment by caoxiang93** [comment]
maxgraph-coordinator.log
2022-05-17 11:33:51,039 INFO [] [maxgraph-master-service-0] [MasterService] - Master service scheduling...
2022-05-17 11:33:56,041 INFO [] [maxgraph-master-service-0] [MasterService] - Master service scheduling...
2022-05-17 11:34:01,041 INFO [] [maxgraph-master-service-0] [MasterService] - Master service scheduling...
                                                                                                                                                                                                        31,1           0%
2022-05-17 11:44:25,767 INFO [] [grpc-worker--0] [PegasusRuntimeManager] - Response to timely worker 0 in group 0, version: 0, ip list: [ip: "10.192.76.144"
store_port: 44286
runtime_port: 41391
] response: addresses {
  ip: "10.192.76.144"
  store_port: 44286
  runtime_port: 41391
}
task_partition_list {
  partition_list: 0
}
task_partition_list {
  task_index: 1
  partition_list: 1
}

2022-05-17 11:44:26,088 INFO [] [maxgraph-master-service-0] [MasterService] - Master service scheduling...
2022-05-17 11:44:27,042 INFO [] [TIMEOUT_MONITOR-0] [WorkerManager] - worker 1 exist time:1275
2022-05-17 11:44:30,042 INFO [] [TIMEOUT_MONITOR-0] [WorkerManager] - worker 1 exist time:4275
2022-05-17 11:44:30,772 INFO [] [grpc-worker--0] [ServerDataApiServer] - serverId is 1 isLegal is true aliveId is 1
2022-05-17 11:44:30,772 INFO [] [grpc-worker--0] [PegasusRuntimeManager] - worker 0 in group 0 is running, ip: 10.192.76.144, port: 41391.
2022-05-17 11:44:30,772 INFO [] [grpc-worker--0] [PegasusRuntimeManager] - Response to timely worker 0 in group 0, version: 0, ip list: [ip: "10.192.76.144"
store_port: 44286
runtime_port: 41391
] response: addresses {
  ip: "10.192.76.144"
  store_port: 44286
  runtime_port: 41391
}
task_partition_list {
  partition_list: 0
}
task_partition_list {
  task_index: 1
  partition_list: 1
}

2022-05-17 11:44:31,089 INFO [] [maxgraph-master-service-0] [MasterService] - Master service scheduling...
2022-05-17 11:44:33,042 INFO [] [TIMEOUT_MONITOR-0] [WorkerManager] - worker 1 exist time:2270
2022-05-17 11:44:35,778 INFO [] [grpc-worker--0] [ServerDataApiServer] - serverId is 1 isLegal is true aliveId is 1
2022-05-17 11:44:35,778 INFO [] [grpc-worker--0] [PegasusRuntimeManager] - worker 0 in group 0 is running, ip: 10.192.76.144, port: 41391.
2022-05-17 11:44:35,779 INFO [] [grpc-worker--0] [PegasusRuntimeManager] - Response to timely worker 0 in group 0, version: 0, ip list: [ip: "10.192.76.144"
store_port: 44286
runtime_port: 41391
] response: addresses {
  ip: "10.192.76.144"
  store_port: 44286
  runtime_port: 41391
}
task_partition_list {
  partition_list: 0
}
task_partition_list {
  task_index: 1
  partition_list: 1
}

2022-05-17 11:44:36,043 INFO [] [TIMEOUT_MONITOR-0] [WorkerManager] - worker 1 exist time:265
2022-05-17 11:44:36,089 INFO [] [maxgraph-master-service-0] [MasterService] - Master service scheduling...
2022-05-17 11:44:39,043 INFO [] [TIMEOUT_MONITOR-0] [WorkerManager] - worker 1 exist time:3265

runtime.log
1652758484882^A12811367659796688^AEXECUTOR^A1^ASERVER_DOWN^A0^A0^A-1^Aworker 0 in group 0 connect to [] success.
1652758484882^A12811367659796688^AEXECUTOR^A1^ASERVER_DOWN^A0^A0^A-1^Aworker is running successfully.

**Comment by lidongze0629** [comment]
@caoxiang93 目前的日志还看不出什么问题，方便的话，可以加一下我们的微信哈，发一份全的日志在详细看看，微信号: graphscope

**Comment by siyuan0322** [comment]
Closed as stale. And there is a new gaia engine replacing the former maxgraph, the issue may have disappeared/resolved.
If you have additional questions please feel free to reopen this.

**Comment by Song-xx** [comment]
I have the same problem,and how do you solve it at last?
