### ISSUE TITLE
[BUG] k8s-ci failed in gremlin query stage

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#1896]
**Describe the bug**

See detailed report in https://github.com/alibaba/GraphScope/runs/7552550498?check_suite_focus=true

```
oading vertex labeled _ and edge labeled _: 100%|██████████| 10/10 [00:02<00:00,  4.07it/s]
2022-07-28 11:19:30,868 [INFO][coordinator:1186]: subgraph has been loaded
Error: -28 03:19:30,898 [ERROR][rpc:187]: Runstep failed with code: INTERACTIVE_ENGINE_INTERNAL_ERROR, message: Error occurred during preprocessing, The traceback is: Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 910, in _fetch_gremlin_result
    rlt = result_set.all().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/graphscope/.local/lib/python3.8/site-packages/gremlin_python/driver/resultset.py", line 90, in cb
    f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/graphscope/.local/lib/python3.8/site-packages/gremlin_python/driver/connection.py", line 83, in _receive
    status_code = self._protocol.data_received(data, self._results)
  File "/home/graphscope/.local/lib/python3.8/site-packages/gremlin_python/driver/protocol.py", line 138, in data_received
    raise GremlinServerError(message['status'])
gremlin_python.driver.protocol.GremlinServerError: 597: op type {class com.alibaba.graphscope.common.intermediate.operator.ScanFusionOp} returns {TableNotExistError, msg is table Str("\u{6}") does not exist}
```

**Additional context**

**Comment by longbinlai** [comment]
Have passed all ci tests before merged. No idea what is the issue? Hi a rerun anyway

**Comment by sighingnow** [comment]
Closing as rerun succeeded.

**Comment by sighingnow** [comment]
The k8s-test keeps failing with the exactly same reason:

- https://github.com/alibaba/GraphScope/runs/7596818539?check_suite_focus=true
- https://github.com/alibaba/GraphScope/runs/7596960999?check_suite_focus=true
