### ISSUE TITLE
[BUG] Create GIE failed using graphscope deployed by helm

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#2161]
**Describe the bug**
deploy with helm on k8s

**To Reproduce**
1. loaded dataset success
2. create GIE failed
```python
# Import the graphscope module
import os
import graphscope
graphscope.set_option(show_log=False)  # enable logging
graphscope.set_option(log_level='DEBUG') # log level
sess = graphscope.session(addr='ip:port',cluster_type='k8s', mount_dataset='/home/data/testingdata')

# Load the obgn_mag dataset as a graph
from graphscope.dataset import load_ogbn_mag
graph = load_ogbn_mag(sess,'/tmp/testingdata/')

# get the entrypoint for submitting Gremlin queries on graph g.
interactive = sess.gremlin(graph)
print(interactive.graph_url)
```

**Expected behavior**
coodinator log
`Create GIE instance with command: /home/graphscope/.local/lib/python3.8/site-packages/graphscope.runtime/bin/giectl create_gremlin_instance_on_k8s /tmp/gs/graphscope-1666685425/session_pkzhchoo 105809399820113850 /tmp/graph_7LaSXd5t.json gs-engine-graphscope-1666685425-7mxj6,gs-engine-graphscope-1666685425-lqspj engine 8239 8240 8241 graphscope-1666685425-coordinator`

juputer log 
``

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: 0.17.0
 - OS: Linux
 - Version [e.g. 10.15]
 - Kubernetes Version 1.19.5

**Additional context**

**Comment by siyuan0322** [comment]
There should be log files within `/home/graphscope/.local/log/graphscope`， could you see if there is some error messages in the logs, and if any please append them there.

**Comment by JackyYangPassion** [comment]
when run this code:
```
interactive = sess.gremlin(graph)
print(interactive.graph_url)
```
when lode data success, create GIE failed .


```
I1025 20:04:17.000000    56 /work/analytical_engine/core/grape_instance.cc:201] Unloading Graph graph_HIGhIh5J
I1025 20:04:17.000000    56 /work/analytical_engine/core/object/gs_object.h:66] Object graph_HIGhIh5J[LabeledFragmentWrapper] is destructed.
2022-10-25 20:04:17,038 [INFO][cluster:393]: Create GIE instance with command: /home/graphscope/.local/lib/python3.8/site-packages/graphscope.runtime/bin/giectl create_gremlin_instance_on_k8s /tmp/gs/graphscope-1666698252/session_nvgrmkqz 79504033283502212 /tmp/graph_5LnIMIQu.json gs-engine-graphscope-1666698252-c8gr5,gs-engine-graphscope-1666698252-jn8lw engine 8236 8237 8238 graphscope-1666698252-coordinator
2022-10-25 20:14:18,909 [INFO][cluster:420]: Close GIE instance with command: /home/graphscope/.local/lib/python3.8/site-packages/graphscope.runtime/bin/giectl close_gremlin_instance_on_k8s /tmp/gs/graphscope-1666698252/session_nvgrmkqz 79504033283502212 gs-engine-graphscope-1666698252-c8gr5,gs-engine-graphscope-1666698252-jn8lw engine
2022-10-25 20:14:18,919 [ERROR][rpc:189]: Runstep failed with code: INTERACTIVE_ENGINE_INTERNAL_ERROR, message: Error occurred during preprocessing, The traceback is: Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 871, in _create_interactive_instance
    if check_gremlin_server_ready(maxgraph_endpoint):
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/utils.py", line 2000, in check_gremlin_server_ready
    raise TimeoutError(f"Gremlin check query failed: {error_message}")
TimeoutError: Gremlin check query failed: Cannot connect to host 10.100.246.135:8238 ssl:default [Connect call failed ('10.100.246.135', 8238)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 642, in _RunStep
    head, bodies = self.run_on_interactive_engine(dag)
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/monitor.py", line 213, in runOnInteractiveEngineWarp
    res = func(instance, dag_def)
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 527, in run_on_interactive_engine
    op_result = self._create_interactive_instance(op)
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 896, in _create_interactive_instance
    raise RuntimeError("Create interactive instance failed.") from e
RuntimeError: Create interactive instance failed.
```

**Comment by JackyYangPassion** [comment]
> There should be log files within `/home/graphscope/.local/log/graphscope`， could you see if there is some error messages in the logs, and if any please append them there.

i'm not file this path on K8S pod: coodinator and graph engine role

**Comment by JackyYangPassion** [comment]
coodinator log:
path:
`/var/log/graphscope/`

log:
```
[main] INFO com.alibaba.graphscope.frontend.Frontend - start to run Frontend.
[main] INFO com.alibaba.graphscope.frontend.Frontend - Configs {frontend.service.port=, graph.schema=/tmp/graph_K8u2yWBj.json, pegasus.hosts=8244, pegasus.worker.num=2, pegasus.output.capacity=16, pegasus.timeout=240000, pegasus.batch.size=1024}
[main] INFO com.alibaba.graphscope.frontend.Frontend - Read schema from vineyard schema file /tmp/graph_K8u2yWBj.json
[main] ERROR com.alibaba.graphscope.frontend.Frontend - Error in frontend main:
java.lang.IllegalArgumentException: key [frontend.service.port] val [] parse failed
        at com.alibaba.graphscope.common.config.Config.get(Config.java:39)
        at com.alibaba.graphscope.frontend.Frontend.start(Frontend.java:38)
        at com.alibaba.graphscope.frontend.Frontend.main(Frontend.java:59)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.alibaba.graphscope.common.config.Config.lambda$intConfig$1(Config.java:49)
        at com.alibaba.graphscope.common.config.Config.get(Config.java:36)
        ... 2 more
```

**Comment by JackyYangPassion** [comment]
gs-engine log:
path:
/var/log/graphscope/

log file  
cat executor.log 
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', v6d/src/bin/gaia_executor.rs:69:5
stack backtrace:
   0:     0x5640870e2431 - <unknown>
   1:     0x56408684c77c - <unknown>
   2:     0x5640870bb959 - <unknown>
   3:     0x5640870e35c2 - <unknown>
   4:     0x5640870e462a - <unknown>
   5:     0x5640870e4072 - <unknown>
   6:     0x5640870e3fe6 - <unknown>
   7:     0x5640870e3fa2 - <unknown>
   8:     0x5640865d0ad2 - <unknown>
   9:     0x56408684c46b - <unknown>
  10:     0x5640865cf97a - <unknown>
  11:     0x56408663a875 - <unknown>
  12:     0x56408663247d - <unknown>
  13:     0x5640867f9de3 - <unknown>
  14:     0x5640867f9ced - <unknown>
  15:     0x564086811579 - <unknown>
  16:     0x7f9e7db16083 - __libc_start_main
  17:     0x56408660579f - <unknown>
  18:                0x0 - <unknown>
```

**Comment by siyuan0322** [comment]
How do you deploy your cluster, via helm?

**Comment by JackyYangPassion** [comment]
> 

yes

**Comment by siyuan0322** [comment]
Could you share your deployment configuration so that I could reproduce?

**Comment by JackyYangPassion** [comment]
follow this step:
```
1. K8S 集群
2. 按照命令安装 graphscope 
   wget https://get.helm.sh/helm-v3.8.1-linux-amd64.tar.gz

   ##安装helm
   tar -zxvf helm-v3.8.1-linux-amd64.tar.gz 
   cp linux-amd64/helm /usr/local/bin/
   chmod +x /usr/local/bin/helm 

   ##拉取镜像
   helm version
   helm repo add graphscope https://graphscope.oss-cn-beijing.aliyuncs.com/charts/
   helm repo update
   helm search repo graphscope

## 创建namespace
   kubectl create namespace testgraphscope

   ## 安装组件
   helm install graphscope graphscope/graphscope --namespace=testgraphscope --version=0.17.0
   
```

after commite python code with jupyter

**Comment by siyuan0322** [comment]
Thanks for the report, I will look into that.

**Comment by JackyYangPassion** [comment]
> Thanks for the report, I will look into that.
3Q

**Comment by siyuan0322** [comment]
Hi @JackyYangPassion I have a fix in #2171.
You could pull the charts to local and apply the fix or just checkout this branch, and install this local charts by `helm install my-release ./GraphScope/charts/graphscope`

**Comment by JackyYangPassion** [comment]
> pull the charts to local and apply the fix

how can do first method
```
You could pull the charts to local and apply the fix 
```

when checkout this branch and install charts by helm install my-release ./GraphScope/charts/graphscope --version=0.17.0

```
Failed to pull image "registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.18.0": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.18.0 not found: manifest unknown: manifest unknown
```
how can use 0.17.0 ?

**Comment by siyuan0322** [comment]
I'm sorry as I forgot that the branch is based on main rather than 0.17.0.
For a quick fix you find this file in `GraphScope/charts/graphscope/Chart.yaml` and change these two `0.18.0` to `0.17.0`
https://github.com/alibaba/GraphScope/blob/89a4a218e9e468f610b80e1beb740135606c5478/charts/graphscope/Chart.yaml#L29-L35

**Comment by JackyYangPassion** [comment]
> ```python
> # Import the graphscope module
> import os
> import graphscope
> graphscope.set_option(show_log=False)  # enable logging
> graphscope.set_option(log_level='DEBUG') # log level
> sess = graphscope.session(addr='ip:port',cluster_type='k8s', mount_dataset='/home/data/testingdata')
> 
> # Load the obgn_mag dataset as a graph
> from graphscope.dataset import load_ogbn_mag
> graph = load_ogbn_mag(sess,'/tmp/testingdata/')
> 
> # get the entrypoint for submitting Gremlin queries on graph g.
> interactive = sess.gremlin(graph)
> print(interactive.graph_url)
> ```

coodinator log
```
[main] INFO com.alibaba.graphscope.frontend.Frontend - start to run Frontend.
[main] INFO com.alibaba.graphscope.frontend.Frontend - Configs {frontend.service.port=, graph.schema=/tmp/graph_pPIhMFSv.json, pegasus.hosts=8235, pegasus.worker.num=2, pegasus.output.capacity=16, pegasus.timeout=240000, pegasus.batch.size=1024}
[main] INFO com.alibaba.graphscope.frontend.Frontend - Read schema from vineyard schema file /tmp/graph_pPIhMFSv.json
[main] ERROR com.alibaba.graphscope.frontend.Frontend - Error in frontend main:
java.lang.IllegalArgumentException: key [frontend.service.port] val [] parse failed
        at com.alibaba.graphscope.common.config.Config.get(Config.java:39)
        at com.alibaba.graphscope.frontend.Frontend.start(Frontend.java:38)
        at com.alibaba.graphscope.frontend.Frontend.main(Frontend.java:59)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.alibaba.graphscope.common.config.Config.lambda$intConfig$1(Config.java:49)
        at com.alibaba.graphscope.common.config.Config.get(Config.java:36)
        ... 2 more
```

**Comment by JackyYangPassion** [comment]
> I'm sorry as I forgot that the branch is based on main rather than 0.17.0. For a quick fix you find this file in `GraphScope/charts/graphscope/Chart.yaml` and change these two `0.18.0` to `0.17.0`
> 
> https://github.com/alibaba/GraphScope/blob/89a4a218e9e468f610b80e1beb740135606c5478/charts/graphscope/Chart.yaml#L29-L35

create GIE with same error after 10 minute
coodinator log
```
[main] INFO com.alibaba.graphscope.frontend.Frontend - start to run Frontend.
[main] INFO com.alibaba.graphscope.frontend.Frontend - Configs {frontend.service.port=, graph.schema=/tmp/graph_pPIhMFSv.json, pegasus.hosts=8235, pegasus.worker.num=2, pegasus.output.capacity=16, pegasus.timeout=240000, pegasus.batch.size=1024}
[main] INFO com.alibaba.graphscope.frontend.Frontend - Read schema from vineyard schema file /tmp/graph_pPIhMFSv.json
[main] ERROR com.alibaba.graphscope.frontend.Frontend - Error in frontend main:
java.lang.IllegalArgumentException: key [frontend.service.port] val [] parse failed
        at com.alibaba.graphscope.common.config.Config.get(Config.java:39)
        at com.alibaba.graphscope.frontend.Frontend.start(Frontend.java:38)
        at com.alibaba.graphscope.frontend.Frontend.main(Frontend.java:59)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.alibaba.graphscope.common.config.Config.lambda$intConfig$1(Config.java:49)
        at com.alibaba.graphscope.common.config.Config.get(Config.java:36)
        ... 2 more
```

**Comment by siyuan0322** [comment]
Weird, I could not reproduce this time. Could you show me the pods, services, deployments of yours?
```bash
kubectl -n testgraphscope get svc
kubectl -n testgraphscope get pod
kubectl -n testgraphscope get deployment
```

**Comment by JackyYangPassion** [comment]
![image](https://user-images.githubusercontent.com/13795366/198029741-bbc75713-6aa3-4e95-8c86-f723d18f432f.png)

**Comment by JackyYangPassion** [comment]
> 



> Weird, I could not reproduce this time. Could you show me the pods, services, deployments of yours?
> 
> ```shell
> kubectl -n testgraphscope get svc
> kubectl -n testgraphscope get pod
> kubectl -n testgraphscope get deployment
> ```

the result on picture

**Comment by siyuan0322** [comment]
Seems you doesn't apply the fix, as the coordinator name should be `coordinator-graphscope1` after the fix. What branch did you checked out? 
`git clone -b zsy/helm https://github.com/siyuan0322/graphscope`

**Comment by JackyYangPassion** [comment]
It's running,Create GIE success!!
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/13795366/198045310-c481297f-fec5-4a68-858c-bc1d6ca8955c.png">

 

> Seems you doesn't apply the fix, as the coordinator name should be `coordinator-graphscope1` after the fix. What branch did you checked out? It haven't been merged to main yet. `git clone -b zsy/helm https://github.com/siyuan0322/graphscope`
