### ISSUE TITLE
[BUG] [GraphScope-0.18.0a20221102]Load HDFS Data failed Install GraphScope locally without Kubernetes

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#2193]
**Describe the bug**
deploy locally without K8S

**To Reproduce**
1. loaded data from HDFS failed
```python
# Install graphscope package if you are NOT in the Playground
!pip3 install -U graphscope --pre
!pip3 install -U graphscope-client --pre

# Import the graphscope module
import graphscope
import os
from graphscope.client.session import get_default_session
# 单机验证 加载图数据 from HDFS
from graphscope.framework.loader import Loader

graphscope.set_option(show_log=True)  # enable logging

sess = get_default_session()
graph = sess.g()

graph = (
        graph.add_vertices(Loader("hdfs:///home/ogbn_mag_small/paper.csv",host="xxx", port=9000), "paper")
        .add_vertices(Loader("hdfs:///home/ogbn_mag_small/author.csv",host="xxx", port=9000), "author")
        .add_vertices(Loader("hdfs:///home/ogbn_mag_small/institution.csv",host="xxx", port=9000), "institution")
        .add_vertices(Loader("hdfs:///home/ogbn_mag_small/field_of_study.csv",host="xxx", port=9000), "field_of_study")
        .add_edges(
            Loader("hdfs:///home/ogbn_mag_small/author_affiliated_with_institution.csv",host="xxx", port=9000),
            "affiliated",
            src_label="author",
            dst_label="institution",
        )
        .add_edges(
            Loader("hdfs:///home/ogbn_mag_small/paper_has_topic_field_of_study.csv",host="xxx", port=9000),
            "hasTopic",
            src_label="paper",
            dst_label="field_of_study",
        )
        .add_edges(
            Loader("hdfs:///home/ogbn_mag_small/paper_cites_paper.csv",host="xxx", port=9000),
            "cites",
            src_label="paper",
            dst_label="paper",
        )
        .add_edges(
            Loader("hdfs:///home/ogbn_mag_small/author_writes_paper.csv",host="xxx", port=9000),
            "writes",
            src_label="author",
            dst_label="paper",
        )
    )
```

**Expected behavior**
juputer log 

```
2022-11-03 10:32:02,958 [ERROR][rpc:186]: Runstep failed with code: COORDINATOR_INTERNAL_ERROR, message: Error occurred during RunStep, The traceback is: Traceback (most recent call last):
  File "/home/data/anaconda3/lib/python3.9/site-packages/gscoordinator/coordinator.py", line 304, in _RunStep
    head, bodies = self._operation_executor.run_on_coordinator(
  File "/home/data/anaconda3/lib/python3.9/site-packages/gscoordinator/op_executor.py", line 684, in run_on_coordinator
    op_result = self._process_data_source(op, dag_bodies, loader_op_bodies)
  File "/home/data/anaconda3/lib/python3.9/site-packages/gscoordinator/op_executor.py", line 792, in _process_data_source
    _process_loader_func(loader, vineyard_endpoint, vineyard_ipc_socket)
  File "/home/data/anaconda3/lib/python3.9/site-packages/gscoordinator/op_executor.py", line 765, in _process_loader_func
    new_protocol, new_source = _spawn_vineyard_io_stream(
  File "/home/data/anaconda3/lib/python3.9/site-packages/gscoordinator/op_executor.py", line 740, in _spawn_vineyard_io_stream
    vineyard.io.open(
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/io/stream.py", line 157, in open
    return read(path, *args, handlers=handlers, **kwargs)
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/core/driver.py", line 127, in wrap
    return func(*args, **kwargs)
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/io/stream.py", line 72, in read
    raise RuntimeError(
RuntimeError: Unable to find a proper IO driver for hdfs:///home/ogbn_mag_small/paper.csv, potential causes are:
 read_dataframe: Traceback (most recent call last):
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/io/stream.py", line 61, in read
    r = reader(
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/drivers/io/stream.py", line 311, in read_dataframe
    stream = read_bytes(
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/drivers/io/stream.py", line 268, in read_bytes
    return launcher.wait()
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/drivers/io/stream.py", line 169, in wait
    r = proc.wait(timeout=timeout)
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/drivers/io/stream.py", line 65, in wait
    return vineyard.ObjectID(super().wait(timeout=timeout))
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/launcher/script.py", line 138, in wait
    raise RuntimeError(
RuntimeError: Failed to launch job [/home/data/anaconda3/lib/python3.9/site-packages/vineyard/drivers/io/ssh.sh localhost vineyard_read_bytes /tmp/vineyard.sock.1667442393.493992 "hdfs:///home/ogbn_mag_small/paper.csv" ...], exited with 255: 
loadFileSystems error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
hdfsBuilderConnect(forceNewInstance=1, nn=hdfs://xxx, port=9000, kerbTicketCachePath=(NULL), userName=(NULL)) error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
/arrow/cpp/src/arrow/filesystem/hdfs.cc:52: Failed to disconnect hdfs client: IOError: HDFS hdfsFS::Disconnect failed, errno: 9 (Bad file descriptor)

extra diagnostics are as follows: Cannot initialize such filesystem for 'hdfs:///home/ogbn_mag_small/paper.csv', exception is:
Traceback (most recent call last):
  File "/home/data/anaconda3/lib/python3.9/site-packages/vineyard/drivers/io/adaptors/read_bytes.py", line 130, in read_bytes
    fs = fsspec.filesystem(protocol, **storage_options)
  File "/home/data/anaconda3/lib/python3.9/site-packages/fsspec/registry.py", line 284, in filesystem
    return cls(**storage_options)
  File "/home/data/anaconda3/lib/python3.9/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/data/anaconda3/lib/python3.9/site-packages/fsspec/implementations/arrow.py", line 235, in __init__
    fs = HadoopFileSystem(
  File "pyarrow/_hdfs.pyx", line 89, in pyarrow._hdfs.HadoopFileSystem.__init__
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: HDFS connection failed
```

``

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: 0.18.0a20221102
 - OS: Linux
 - HDFS version: 3.2.2 

**Additional context**

**Comment by sighingnow** [comment]
Please ensure your classpath for hadoop is correctly exported.

```
export CLASSPATH="$($HADOOP_HOME/bin/hdfs classpath --glob)"
```

**Comment by JackyYangPassion** [comment]
thanks!
I'm testing.
there are tow questions:
1. Do you also need to configure $HADOOP_HOME when deploying through k8?
2. Is there any framework and code interpretation article in the community, I want to be able to Trouble Shotting quickly

**Comment by JackyYangPassion** [comment]
> Please ensure your classpath for hadoop is correctly exported.
> 
> ```
> export CLASSPATH="$($HADOOP_HOME/bin/hdfs classpath --glob)"
> ```

add CLASSPATH=.$CLASSPATH:"$($HADOOP_HOME/bin/hdfs classpath --glob)"  /etc/profile
source /etc/profile

lunch jupyter

it's running 
![image](https://user-images.githubusercontent.com/13795366/199668035-6baab511-53c2-405f-b1d5-43e155da8779.png)

**Comment by sighingnow** [comment]
@JackyYangPassion Thanks for the feedback!

Closing as resolved.

**Comment by sighingnow** [comment]
> thanks! I'm testing. there are tow questions:
> 
> 1. Do you also need to configure $HADOOP_HOME when deploying through k8?

Our official docker image have already sourced the environment, see our test case on Kubernetes: https://github.com/alibaba/GraphScope/blob/main/python/graphscope/tests/kubernetes/test_demo_script.py#L116

> 2. Is there any framework and code interpretation article in the community, I want to be able to Trouble Shotting quickly

Please refer to our wechat public account "GraphScope".

We have [documentation](https://graphscope.io/docs/) and [blogs](https://graphscope.io/blog/) as well.
