### ISSUE TITLE
[BUG] GraphLearn doesn't work with Python 3.10 & Python 3.11

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#2391]
**Describe the bug**

GraphLearn requires a fairly low version of tensorflow (currently 2.5.2 in our CI) which is not compatible with Python 3.10 and Python 3.11.

We'll release the wheel packages for Python 3.{10,11} to pypi and that would be a concern if user tries to play with the GLE part with recently Python distributions.

For detail error message, just trying `pip3 install grpahscope>=0.19.0 tensorflow` in Python 3.{10,11} environments and try the demo in README.

**Additional context**

**Comment by goldenleaves** [comment]
I reproduced this example with ubuntu 22.04 and Python 3.10, and got the following error info:
```
Traceback (most recent call last):
  File "/root/workdir/codelab/test_gle.py", line 104, in <module>
    train_gcn(lg, node_type="paper", edge_type="cites",
  File "/root/workdir/codelab/test_gle.py", line 73, in train_gcn
    train_data = EgoSAGESupervisedDataLoader(
  File "/root/workdir/pip/graphscope/graphscope/learning/examples/tf/ego_sage/ego_sage_data_loader.py", line 47, in __init__
    super().__init__(graph, mask, sampler, batch_size, window)
  File "/root/workdir/pip/graphscope/graphscope/learning/examples/tf/ego_data_loader.py", line 54, in __init__
    self._dataset = tfg.Dataset(self._q, window=window)
  File "/root/workdir/pip/graphscope/graphscope/learning/graphlearn/python/nn/tf/data/dataset.py", line 64, in __init__
    self._iterator = self._make_iterator()
  File "/root/workdir/pip/graphscope/graphscope/learning/graphlearn/python/nn/tf/data/dataset.py", line 167, in _make_iterator
    output_types, output_shapes = self._raw_flatten_types_and_shapes()
  File "/root/workdir/pip/graphscope/graphscope/learning/graphlearn/python/nn/tf/data/dataset.py", line 183, in _raw_flatten_types_and_shapes
    types, shapes = self._data_types_and_shapes(node.decoder, 
  File "/root/workdir/pip/graphscope/graphscope/learning/graphlearn/python/nn/tf/data/dataset.py", line 236, in _data_types_and_shapes
    feat_shapes = np.array([tf.TensorShape([None, node_decoder.int_attr_num]),
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
```
Is this consistent with the problem you encountered? @sighingnow

**Comment by goldenleaves** [comment]
I have located the problem and will fix it as soon as possible

**Comment by sighingnow** [comment]
After fixing the above error, new tensorflow related error would appear.

Thanks!

**Comment by goldenleaves** [comment]
fixed with https://github.com/alibaba/graph-learn/pull/249
