### ISSUE TITLE
[BUG] Use Graphscope session to deploy on k8s faild

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#2405]
**Describe the bug**
use graphscope session to deploy on k8s faild

**To Reproduce**
```
session = graphscope.session(
       k8s_coordinator_cpu=1,
       k8s_coordinator_mem="1Gi",
       k8s_vineyard_cpu=0.2,
       k8s_vineyard_mem="1Gi",
       vineyard_shared_mem="2Gi",
       k8s_engine_cpu=0.2,
       k8s_engine_mem="1Gi",
       num_workers=1,
       k8s_namespace='gstest008',
       k8s_client_config={"config_file": '/usr/local/airflow/dags/k8s_config'})
```

log
```
2023-02-03 10:38:16,037 [INFO][kubernetes_launcher:904]: Creating engine replicaset...
2023-02-03 10:38:16,037 [INFO][kubernetes_launcher:552]: Launching GraphScope engines pod ...
2023-02-03 10:38:16,319 [INFO][kubernetes_launcher:957]: [gs-engine-zeqimz-nh2q4]: Successfully assigned gstest008/gs-engine-zeqimz-nh2q4 to k8s-worker2
2023-02-03 10:38:16,989 [INFO][kubernetes_launcher:957]: [gs-engine-zeqimz-nh2q4]: Container image "registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.18.0" already present on machine
2023-02-03 10:38:17,036 [INFO][kubernetes_launcher:957]: [gs-engine-zeqimz-nh2q4]: Created container engine
2023-02-03 10:38:17,127 [INFO][kubernetes_launcher:957]: [gs-engine-zeqimz-nh2q4]: Started container engine
2023-02-03 10:38:17,155 [INFO][kubernetes_launcher:957]: [gs-engine-zeqimz-nh2q4]: Created container vineyard
2023-02-03 10:38:17,247 [INFO][kubernetes_launcher:957]: [gs-engine-zeqimz-nh2q4]: Started container vineyard
2023-02-03 10:38:29,072 [INFO][kubernetes_launcher:957]: [gs-engine-zeqimz-nh2q4]: Readiness probe failed:
2023-02-03 10:47:55,414 [INFO][coordinator:473]: Cleaning up resources in coordinator
2023-02-03 10:47:55,717 [INFO][kubernetes_launcher:1169]: Dangling coordinator detected, cleaning up...
2023-02-03 10:48:02,766 [INFO][kubernetes_launcher:1023]: Starting GAE rpc service on None ...
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/utils.py", line 386, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/session.py", line 674, in __init__
    self._connect()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/session.py", line 1055, in _connect
    ) = self._grpc_client.create_analytical_instance()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/rpc.py", line 199, in create_analytical_instance
    response = self._stub.CreateAnalyticalInstance(request)
  File "/usr/local/lib64/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.ABORTED
	details = "'NoneType' object is not iterable"
	debug_error_string = "{"created":"@1675392482.768336939","description":"Error received from peer ipv4:172.31.48.79:31219","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"'NoneType' object is not iterable","grpc_status":10}"
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: v0.18.0
 - OS: linux
 - Kubernetes Version: 1.25.4

**Comment by siyuan0322** [comment]
There are two possible solution.
1. Could you upgrade to 0.19.0 and see if that error is still exists
2. Could you try again and while pending, open another terminal and watch the log of the coordinator pod, like this `kubectl -n gstest008 logs -f xxx-coordinator-xxx`. replace `xxx-coordinator-xxx` to the name of the coordinator pod. And please paste that log to here.

**Comment by JackyYangPassion** [comment]
kubectl -n gstest008 logs -f xxx-coordinator-xxx

```
2023-02-03 11:46:59,980 [INFO][coordinator:913]: Coordinator server listen at 0.0.0.0:59464
2023-02-03 11:47:17,650 [INFO][kubernetes_launcher:715]: Launching etcd ...
2023-02-03 11:47:18,747 [INFO][kubernetes_launcher:879]: etcd cluster created
2023-02-03 11:47:18,747 [INFO][kubernetes_launcher:883]: etcd endpoint is 10.107.166.185:2379
2023-02-03 11:47:18,747 [INFO][kubernetes_launcher:904]: Creating engine replicaset...
2023-02-03 11:47:18,747 [INFO][kubernetes_launcher:552]: Launching GraphScope engines pod ...
2023-02-03 11:47:19,104 [INFO][kubernetes_launcher:957]: [gs-engine-ijdtbf-9dsr5]: Successfully assigned gstest008/gs-engine-ijdtbf-9dsr5 to k8s-worker2
2023-02-03 11:47:19,679 [INFO][kubernetes_launcher:957]: [gs-engine-ijdtbf-9dsr5]: Container image "registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.18.0" already present on machine
2023-02-03 11:47:19,709 [INFO][kubernetes_launcher:957]: [gs-engine-ijdtbf-9dsr5]: Created container engine
2023-02-03 11:47:19,838 [INFO][kubernetes_launcher:957]: [gs-engine-ijdtbf-9dsr5]: Started container engine
2023-02-03 11:47:19,844 [INFO][kubernetes_launcher:957]: [gs-engine-ijdtbf-9dsr5]: Created container vineyard
2023-02-03 11:47:19,963 [INFO][kubernetes_launcher:957]: [gs-engine-ijdtbf-9dsr5]: Started container vineyard
2023-02-03 11:47:29,278 [INFO][kubernetes_launcher:957]: [gs-engine-ijdtbf-9dsr5]: Readiness probe failed: 
2023-02-03 11:56:59,954 [INFO][coordinator:473]: Cleaning up resources in coordinator
2023-02-03 11:57:00,302 [INFO][kubernetes_launcher:1169]: Dangling coordinator detected, cleaning up...
2023-02-03 11:57:13,303 [ERROR][kubernetes_launcher:1148]: Error when launching GraphScope on kubernetes cluster: ApiException(), with traceback: Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/kubernetes_launcher.py", line 1144, in start
    self._waiting_for_services_ready()
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/kubernetes_launcher.py", line 916, in _waiting_for_services_ready
    replicasets = self._app_api.list_namespaced_replica_set(
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api/apps_v1_api.py", line 3428, in list_namespaced_replica_set
    return self.list_namespaced_replica_set_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api/apps_v1_api.py", line 3539, in list_namespaced_replica_set_with_http_info
    return self.api_client.call_api(
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1543b4f8-0ed8-4e06-ba9f-c379ae5b139b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '7534bebf-0649-42ce-8d42-14e0fed2db90', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'c1baa270-a9d2-4738-92c8-e9350f8798a4', 'Date': 'Fri, 03 Feb 2023 03:57:12 GMT', 'Content-Length': '331'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"replicasets.apps is forbidden: User \"system:serviceaccount:gstest008:default\" cannot list resource \"replicasets\" in API group \"apps\" in the namespace \"gstest008\"","reason":"Forbidden","details":{"group":"apps","kind":"replicasets"},"code":403}



2023-02-03 11:57:13,303 [ERROR][kubernetes_launcher:1148]: Error when launching GraphScope on kubernetes cluster: ApiException(), with traceback: Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/kubernetes_launcher.py", line 1144, in start
    self._waiting_for_services_ready()
  File "/home/graphscope/.local/lib/python3.8/site-packages/gscoordinator/kubernetes_launcher.py", line 916, in _waiting_for_services_ready
    replicasets = self._app_api.list_namespaced_replica_set(
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api/apps_v1_api.py", line 3428, in list_namespaced_replica_set
    return self.list_namespaced_replica_set_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api/apps_v1_api.py", line 3539, in list_namespaced_replica_set_with_http_info
    return self.api_client.call_api(
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/graphscope/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1543b4f8-0ed8-4e06-ba9f-c379ae5b139b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '7534bebf-0649-42ce-8d42-14e0fed2db90', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'c1baa270-a9d2-4738-92c8-e9350f8798a4', 'Date': 'Fri, 03 Feb 2023 03:57:12 GMT', 'Content-Length': '331'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"replicasets.apps is forbidden: User \"system:serviceaccount:gstest008:default\" cannot list resource \"replicasets\" in API group \"apps\" in the namespace \"gstest008\"","reason":"Forbidden","details":{"group":"apps","kind":"replicasets"},"code":403}



2023-02-03 11:57:13,311 [INFO][kubernetes_launcher:1023]: Starting GAE rpc service on None ...
2023-02-03 11:57:13,314 [INFO][coordinator:473]: Cleaning up resources in coordinator
2023-02-03 11:57:14,243 [INFO][coordinator:473]: Cleaning up resources in coordinator
```

**Comment by JackyYangPassion** [comment]
graphscope 0.19.0

```
2023-02-03 04:32:10,884 [INFO][cluster:583]: Stopped coordinator
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 538, in start
    self._create_services()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 450, in _create_services
    self._create_coordinator()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 312, in _create_coordinator
    deployment = coordinator.get_coordinator_deployment()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/resource_builder.py", line 348, in get_coordinator_deployment
    spec = self.get_coordinator_deployment_spec(self._replicas)
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/resource_builder.py", line 343, in get_coordinator_deployment_spec
    template = self.get_coordinator_pod_template_spec()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/resource_builder.py", line 339, in get_coordinator_pod_template_spec
    spec = self.get_coordinator_pod_spec()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/resource_builder.py", line 331, in get_coordinator_pod_spec
    container = self.get_coordinator_container()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/resource_builder.py", line 308, in get_coordinator_container
    lifecycle = self.get_lifecycle()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/resource_builder.py", line 302, in get_lifecycle
    lifecycle_handler = ResourceBuilder.get_lifecycle_handler(_exec)
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/resource_builder.py", line 105, in get_lifecycle_handler
    handler = kube_client.V1LifecycleHandler(_exec=_exec, http_get=http_get, tcp_socket=tcp_socket)
AttributeError: module 'kubernetes.client' has no attribute 'V1LifecycleHandler'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/utils.py", line 386, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/session.py", line 683, in __init__
    self._connect()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/session.py", line 1042, in _connect
    self._launcher.start()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/deploy/kubernetes/cluster.py", line 552, in start
    ) from e
graphscope.framework.errors.K8sError: Error when launching Coordinator on kubernetes cluster

```

**Comment by siyuan0322** [comment]
> User \"system:serviceaccount:gstest008:default\" cannot list resource \"replicasets\" in API group \"apps\" in the namespace

The error reason in 0.18.0 looks like a role permission is missing.
What is your client version?

**Comment by siyuan0322** [comment]
> AttributeError: module 'kubernetes.client' has no attribute 'V1LifecycleHandler'
What's your `Kubernetes` version
`python3 -c  "import kubernetes; print(Kubernetes.__version__)"`
Try upgrade Kubernetes by `python3 -m pip install Kubernetes --upgrade`

**Comment by JackyYangPassion** [comment]
> > AttributeError: module 'kubernetes.client' has no attribute 'V1LifecycleHandler'
> 
> What's your `Kubernetes` version `python3 -c "import kubernetes; print(Kubernetes.__version__)"` Try upgrade kubernetes by `python3 -m pip install kubernetes --upgrade`

python3 -c  "import kubernetes; print(kubernetes.__version__)"
12.0.1

**Comment by JackyYangPassion** [comment]
> > User "system:serviceaccount:gstest008:default" cannot list resource "replicasets" in API group "apps" in the namespace
> 
> The error reason in 0.18.0 looks like a role permission is missing. What is your client version?

graphscope-client==0.18.0

**Comment by siyuan0322** [comment]
Okay, First of all you need to ensure you use 0.18.0 client to call a 0.18.0 image, and 0.19.0 client with a 0.19.0 image, or it couldn't be launched for sure.
I suggest you install the 0.19.0 client and use the 0.19.0 image, since it's the latest version. `python3 -m pip install graphscope-client --upgrade`. and upgrade the kubernetes library `python3 -m pip install kubernetes --upgrade`. Then give it's a try, and monitor the log of coordinator pod.

**Comment by siyuan0322** [comment]
And it reminds me that I need to add a minimum required version of kubernetes library for the client. Thanks for that.

**Comment by JackyYangPassion** [comment]
> And it reminds me that I need to add a minimum required version of kubernetes library for the client. Thanks for that.

i want to run 0.19.0 now.how can do this?

**Comment by siyuan0322** [comment]
> I suggest you install the 0.19.0 client and use the 0.19.0 image, since it's the latest version. python3 -m pip install graphscope-client --upgrade. and upgrade the kubernetes library python3 -m pip install kubernetes --upgrade. Then give it's a try, and monitor the log of coordinator pod.

See this.

**Comment by JackyYangPassion** [comment]
> Okay, First of all you need to ensure you use 0.18.0 client to call a 0.18.0 image, and 0.19.0 client with a 0.19.0 image, or it couldn't be launched for sure. I suggest you install the 0.19.0 client and use the 0.19.0 image, since it's the latest version. `python3 -m pip install graphscope-client --upgrade`. and upgrade the kubernetes library `python3 -m pip install kubernetes --upgrade`. Then give it's a try, and monitor the log of coordinator pod.

"Invalid","details":{"name":"gs-engine-cygcnv","group":"apps","kind":"ReplicaSet","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"1Gi\": must be less than or equal to memory limit","field":"spec.template.spec.containers[0].resources.requests"}]},"code":422}

**Comment by JackyYangPassion** [comment]
> > User "system:serviceaccount:gstest008:default" cannot list resource "replicasets" in API group "apps" in the namespace
> 
> The error reason in 0.18.0 looks like a role permission is missing. What is your client version?

Because the firewall of a k8s worker node is not closed. when close the firewall ,graphscope 0.18 running.

**Comment by siyuan0322** [comment]
> when close the firewall ,graphscope 0.18 running.
OK, thanks for your investigation.

**Comment by siyuan0322** [comment]
> "1Gi": must be less than or equal to memory limit"

Never seen this :cry: Still looks like a client-server mismatch. You could continue use the 0.18.0. Or remove any previous resources and make sure you are using the 0.19.0 package.
Or maybe remove the memory requirement in your session parameter may bypass this as a temporary solution?

**Comment by JackyYangPassion** [comment]
> > I suggest you install the 0.19.0 client and use the 0.19.0 image, since it's the latest version. python3 -m pip install graphscope-client --upgrade. and upgrade the kubernetes library python3 -m pip install kubernetes --upgrade. Then give it's a try, and monitor the log of coordinator pod.
> 
> See this.

graphscope 0.19 running. thanks!
