### ISSUE TITLE
[BUG] load_ogbn_mag 报错

### ISSUE THREAD

**Issue by ilovecomet** [alibaba/GraphScope#2413]
**Describe the bug**
加载图的时候报错

**To Reproduce**
code如下：
import graphscope
graphscope.set_option(show_log=False)
from graphscope.dataset import load_ogbn_mag
g = load_ogbn_mag()

**Expected behavior**
Loading edge labeled affiliated:   0%|          | 0/10 [00:00<?, ?it/s]
Loading edge labeled affiliated: 100%|██████████| 10/10 [00:00<00:00, 136.56it/s]
*** Aborted at 1675753334 (unix time) try "date -d @1675753334" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGBUS (@0x7f912bf8dff0) received by PID 33686 (TID 0x7f9ac7fff700) from PID 737730544; stack trace: ***
    @     0x7f9ad18af980 (unknown)
    @     0x7f9acf31aa9b (unknown)
    @     0x7f9af3765b38 vineyard::generate_directed_csc<>()
    @     0x7f9af35a7c90 vineyard::ArrowFragment<>::AddNewEdgeLabels()
    @     0x7f9af35ab85f vineyard::ArrowFragment<>::AddEdges()
    @     0x7f9af39011b7 vineyard::BasicEVFragmentLoader<>::AddEdgesToFragment()
    @     0x7f9af3901d9f vineyard::BasicEVFragmentLoader<>::AddVerticesAndEdgesToFragment()
    @     0x7f9af37fb0aa vineyard::ArrowFragmentLoader<>::addVerticesAndEdges()
    @     0x7f9acc6540c2 gs::ArrowFragmentLoader<>::AddLabelsToFragment()
    @     0x7f9acc654197 gs::ArrowFragmentLoader<>::AddLabelsToFragmentAsFragmentGroup()
    @     0x7f9acc5bfc4e AddLabelsToGraph
    @           0x479797 gs::GrapeInstance::addLabelsToGraph()
    @           0x489562 gs::GrapeInstance::OnReceive()
    @           0x508950 gs::Dispatcher::processCmd()
    @           0x50ab66 gs::Dispatcher::publisherLoop()
    @     0x7f9af3b4a4f0 (unknown)
    @     0x7f9ad18a46db start_thread
    @     0x7f9acf2cf61f clone
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/utils.py", line 156, in with_grpc_catch
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/rpc.py", line 184, in _run_step_impl
    response = self._grpc_utils.parse_runstep_responses(
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/utils.py", line 122, in parse_runstep_responses
    for response in responses:
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1675753346.968258046","description":"Error received from peer ipv4:127.0.0.1:59998","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/demo/code/demo.py", line 10, in <module>
    g = load_ogbn_mag()
  File "/usr/local/lib/python3.8/dist-packages/graphscope/dataset/ogbn_mag.py", line 79, in load_ogbn_mag
    graph.add_vertices(os.path.join(prefix, "paper.csv"), "paper")
  File "/usr/local/lib/python3.8/dist-packages/graphscope/framework/graph.py", line 1113, in add_edges
    return self._session._wrapper(
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/session.py", line 941, in _wrapper
    return self.run(dag_node)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/session.py", line 977, in run
    return self.run_fetches(fetches)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/session.py", line 987, in run_fetches
    response = self._grpc_client.run(fetch_handler.targets)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/rpc.py", line 98, in run
    return self._run_step_impl(dag_def)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/utils.py", line 161, in with_grpc_catch
    raise GRPCError(
graphscope.framework.errors.GRPCError: RPC failed: rpc _run_step_impl failed: status <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1675753346.968258046","description":"Error received from peer ipv4:127.0.0.1:59998","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Socket closed","grpc_status":14}"
>
2023-02-07 15:02:31,504 [INFO][coordinator:519]: Clean up resources, cleanup_instance: True, is_dangling: False
2023-02-07 15:02:31,506 [ERROR][coordinator:545]: Cleanup failed, code: UNAVAILABLE, details: failed to connect to all addresses
2023-02-07 15:02:31,506 [ERROR][coordinator:545]: Cleanup failed, code: UNAVAILABLE, details: failed to connect to all addresses
2023-02-07 15:02:31,509 [ERROR][coordinator:545]: Cleanup failed, code: UNAVAILABLE, details: failed to connect to all addresses
2023-02-07 15:02:31,509 [ERROR][coordinator:545]: Cleanup failed, code: UNAVAILABLE, details: failed to connect to all addresses
2023-02-07 15:02:31,515 [INFO][coordinator:519]: Clean up resources, cleanup_instance: True, is_dangling: False
2023-02-07 15:02:31,516 [INFO][coordinator:519]: Clean up resources, cleanup_instance: True, is_dangling: False
**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: 0.19.0
 - OS: Linux ubuntu
 - Version 18.04
 - Kubernetes Version ：单机版(pip安装)

**Additional context**

**Comment by sighingnow** [comment]
Hi @ilovecomet, please add `--shm-size=8g` if you are working inside docker.

**Comment by ilovecomet** [comment]
> 

It's ok, thanks.
