### ISSUE TITLE
[BUG] Fail to run the test_demo_distribute pytest of kubernetes locally

### ISSUE THREAD

**Issue by dashanji** [alibaba/GraphScope#2492]
**Describe the bug**
When I run the test_demo_distribute function using pytest locally, some errors were encountered as follows.

Error 1: [Coordinator] Permisiion denied '/tmp/gs'

```
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/__main__.py", line 3, in <module>
    launch_graphscope()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 862, in launch_graphscope
    launcher = get_launcher(args)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 868, in get_launcher
    launcher = KubernetesClusterLauncher(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/kubernetes_launcher.py", line 219, in __init__
    os.makedirs(self._instance_workspace, exist_ok=True)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/gs'
```
To resolve the error, we could commit the command `sudo chmod /tmp 777` to fix it. But it looks noisy for users, could we use other directories for logging?

Error 2: [GIE] graph_7JncCHry.json: Cannot open: Permission denied
```
====================== FAILURES =======================
______________ test_vineyard_deployment _______________

gs_session_with_vineyard_deployment = {'status': 'active', 'type': 'k8s', 'engine_hosts': 'gs-engine-hkjbjp-0,gs-engine-hkjbjp-1', 'namespace': 'graphscope-...java_sdk': 'OFF', 'engine_hosts': 'gs-engine-hkjbjp-0,gs-engine-hkjbjp-1', 'vineyard_service_name': 'vineyard-hkjbjp'}}
data_dir = '/testingdata/ldbc_sample'
modern_graph_data_dir = '/testingdata/modern_graph'

    def test_vineyard_deployment(gs_session_with_vineyard_deployment, data_dir, modern_graph_data_dir):
        print("Testing vineyard deployment", flush=True)
>       test_demo_distribute(gs_session_with_vineyard_deployment, data_dir, modern_graph_data_dir)

graphscope/tests/kubernetes/test_demo_script.py:224: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
graphscope/tests/kubernetes/test_demo_script.py:230: in test_demo_distribute
    interactive = gs_session_distributed.gremlin(graph)
graphscope/client/session.py:1154: in gremlin
    endpoint = self._grpc_client.create_interactive_instance(object_id, schema_path)
graphscope/client/rpc.py:212: in create_interactive_instance
    response = self._stub.CreateInteractiveInstance(request)
/home/gsbot/.local/lib/python3.8/site-packages/grpc/_channel.py:946: in __call__
    return _end_unary_response_blocking(state, call, False, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

state = <grpc._channel._RPCState object at 0x7f04f5e419d0>
call = <grpc._cython.cygrpc.SegregatedCall object at 0x7f04f5e3f300>
with_call = False, deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
>           raise _InactiveRpcError(state)
E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E               status = StatusCode.ABORTED
E               details = "Create interactive instance failed: Error code: 2, message tar: graph_7JncCHry.json: Cannot open: Permission denied
E           tar: Exiting with failure status due to previous errors
E           command terminated with exit code 2
E           "
E               debug_error_string = "{"created":"@1678203174.528249608","description":"Error received from peer ipv4:172.19.0.3:31058","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Create interactive instance failed: Error code: 2, message tar: graph_7JncCHry.json: Cannot open: Permission denied\ntar: Exiting with failure status due to previous errors\ncommand terminated with exit code 2\n","grpc_status":10}"
E           >
```
It looks like the error is caused by the GIE, I have no idea about it, could you please take a look at this? @siyuan0322 @sighingnow BTW, could we add the test_demo_distribute pytest in the Kubernetes CI to avoid these errors?

**To Reproduce**
1. build the one-node kubernetes cluster using kind with the testingdata volume.
2. build the docker images.
```
export GS_REGISTRY="docker.io"
export GS_TEST_DIR=/testingdata
export GS_TAG="latest"
make -C k8s graphscope
```
3. load the docker images.
```
kind load docker-image docker.io/graphscope/coordinator:latest
kind load docker-image ocker.io/graphscope/analytical:latest
kind load docker-image docker.io/graphscope/interactive-frontend:latest
kind load docker-image docker.io/graphscope/interactive-executor:latest
kind load docker-image docker.io/graphscope/learning:latest
```
4. run pytest
```
python3 -m pytest -s -vvv ./graphscope/tests/kubernetes/test_demo_script.py -k test_demo_distribute
```

**Expected behavior**
Run successfully as expected.

**Environment (please complete the following information):**
 - GraphScope version: [master]
 - OS: [Linux]

**Comment by sighingnow** [comment]
Have been fixed in main in #2477

**Comment by siyuan0322** [comment]
https://github.com/alibaba/GraphScope/pull/2477/files#diff-b46240be91983c83a91766dff53f0e479136a5b3348099a7de4b8e980e3e9619

**Comment by dashanji** [comment]
Thanks, I will try it.

**Comment by sighingnow** [comment]
Closing.
