### ISSUE TITLE
[BUG] failed to launch GAE on Kubernetes when `num_workers=2`

### ISSUE THREAD

**Issue by Qingnan1** [alibaba/GraphScope#2496]
**Describe the bug**
I'm currently following below steps to run Graphscope on K8s
1. sudo pip3 install graphscope
2. from python client
   >>>import graphscope
   >>> graphscope.set_option(show_log=True)
3. open session: 
   >>> sess = graphscope.session(num_workers=2)
4. getting below errors:
2023-03-08 12:13:18,262 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Successfully assigned gs-awqbuz/gs-engine-deyoww-0 to euler47
2023-03-08 12:13:18,993 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Container image "registry.cn-hongkong.aliyuncs.com/graphscope/analytical:0.19.0" already present on machine
2023-03-08 12:13:19,081 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Created container engine
2023-03-08 12:13:19,176 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Started container engine
2023-03-08 12:13:19,179 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Container image "registry.cn-hongkong.aliyuncs.com/graphscope/interactive-executor:0.19.0" already present on machine
2023-03-08 12:13:21,456 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Created container executor
2023-03-08 12:13:21,457 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Started container executor
2023-03-08 12:13:21,459 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Container image "registry.cn-hongkong.aliyuncs.com/graphscope/learning:0.19.0" already present on machine
2023-03-08 12:13:21,460 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Created container learning
2023-03-08 12:13:21,462 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Started container learning
2023-03-08 12:13:21,463 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Container image "vineyardcloudnative/vineyardd:v0.11.7" already present on machine
2023-03-08 12:13:21,464 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Created container vineyard
2023-03-08 12:13:21,466 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-0]: Started container vineyard
2023-03-08 12:13:25,447 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Successfully assigned gs-awqbuz/gs-engine-deyoww-1 to euler48
2023-03-08 12:13:25,448 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Container image "registry.cn-hongkong.aliyuncs.com/graphscope/analytical:0.19.0" already present on machine
2023-03-08 12:13:25,450 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Created container engine
2023-03-08 12:13:25,451 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Started container engine
2023-03-08 12:13:25,453 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Container image "registry.cn-hongkong.aliyuncs.com/graphscope/interactive-executor:0.19.0" already present on machine
2023-03-08 12:13:25,454 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Created container executor
2023-03-08 12:13:25,455 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Started container executor
2023-03-08 12:13:25,457 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Container image "registry.cn-hongkong.aliyuncs.com/graphscope/learning:0.19.0" already present on machine
2023-03-08 12:13:25,494 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Created container learning
2023-03-08 12:13:25,581 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Started container learning
2023-03-08 12:13:25,583 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Container image "vineyardcloudnative/vineyardd:v0.11.7" already present on machine
2023-03-08 12:13:25,644 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Created container vineyard
2023-03-08 12:13:25,739 [INFO][kubernetes_launcher:514]: [gs-engine-deyoww-1]: Started container vineyard
2023-03-08 12:13:32,538 [INFO][kubernetes_launcher:546]: GraphScope engines pod is ready.
2023-03-08 12:13:32,538 [INFO][kubernetes_launcher:547]: Engines pod name list: ['gs-engine-deyoww-0', 'gs-engine-deyoww-1']
2023-03-08 12:13:32,538 [INFO][kubernetes_launcher:548]: Engines pod ip list: ['xxx', 'xxx']
2023-03-08 12:13:32,538 [INFO][kubernetes_launcher:549]: Engines pod host ip list: ['xxx', 'xxx']
2023-03-08 12:13:32,538 [INFO][kubernetes_launcher:550]: Vineyard service endpoint: xxx:31851
2023-03-08 12:13:32,543 [INFO][kubernetes_launcher:570]: Starting GAE rpc service on xxx:56658 ...
2023-03-08 12:13:33,503 [INFO][kubernetes_launcher:598]: **Analytical engine launching command: /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-deyoww-0:1.0,gs-engine-deyoww-1:1.0 /opt/graphscope/bin/grape_engine --host** 0.0.0.0 --port 56658 -v 1 --vineyard_socket /tmp/vineyard_workspace/vineyard.sock
2023-03-08 12:14:34,062 [INFO][coordinator:519]: Clean up resources, cleanup_instance: True, is_dangling: False
2023-03-08 12:14:34,062 [INFO][kubernetes_launcher:693]: Cleaning up kubernetes resources
2023-03-08 20:14:34,257 [INFO][cluster:563]: Stopping coordinator
2023-03-08 20:14:34,298 [INFO][cluster:583]: Stopped coordinator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/utils.py", line 386, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/session.py", line 683, in __init__
    self._connect()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/session.py", line 1081, in _connect
    ) = self._grpc_client.create_analytical_instance()
  File "/usr/local/lib64/python3.7/site-packages/graphscope/client/rpc.py", line 205, in create_analytical_instance
    response = self._stub.CreateAnalyticalInstance(request)
  File "/usr/local/lib64/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.ABORTED
        details = "Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for details"
        **debug_error_string = "{"created":"@1678277674.060117357","description":"Error received from peer ipv4:xxx.xxx.xxx.xxx:32218","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for details","grpc_status":10}"**

**To Reproduce**
check above steps

**Expected behavior**
run graphscope successfly on k8s

**Screenshots**
k8s cluster works fine
![image](https://user-images.githubusercontent.com/44082344/223713037-8c086581-1d2c-4201-a4ef-65cb8ac046c7.png)

**Environment (please complete the following information):**
 - GraphScope version: 0.19.0
 - OS: openeuler
 - Version [e.g. 10.15]
 - Kubernetes Version [v1.23.1]

**Additional context**
**2023-03-08 12:13:33,503 [INFO][kubernetes_launcher:598]: Analytical engine launching command: /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-deyoww-0:1.0,gs-engine-deyoww-1:1.0 /opt/graphscope/bin/grape_engine --host 0.0.0.0 --port 56658 -v 1 --vineyard_socket /tmp/vineyard_workspace/vineyard.sock**
BTW, I saw it is running mpi and graoe_engine from above log details, do I need to install mpi and grape_engine manully?

**Comment by dashanji** [comment]
@Qingnan1  The bug has been fixed in https://github.com/alibaba/GraphScope/pull/2477. and you don't need to install the mpi and grape_engine etc, as they are built in the docker images.

**Comment by sighingnow** [comment]
> @Qingnan1 The bug has been fixed in #2477. and you don't need to install the mpi and grape_engine etc, as they are built in the docker images.

Correct: not fixed by #2477, but should be the same issue with #2479.

**Comment by JackyYangPassion** [comment]
```
session = graphscope.session(
       k8s_coordinator_cpu=1,
       k8s_coordinator_mem="1Gi",
       k8s_vineyard_cpu=0.2,
       k8s_vineyard_mem="1Gi",
       vineyard_shared_mem="2Gi",
       k8s_engine_cpu=0.2,
       k8s_engine_mem="1Gi",
       k8s_image_tag="0.20.0a20230306",
       num_workers=2,
       k8s_namespace='gstest008',
       k8s_client_config={"config_file": '/usr/local/airflow/dags/k8s_config'})
```

gs-engine-qcwcky-0 error log
```
2023-03-13 03:35:48,864 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 0 time
2023-03-13 03:35:48,866 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
10.244.1.178 gs-engine-qcwcky-0
I20230313 11:35:51.482007    61 /home/graphscope/GraphScope/analytical_engine/core/grape_instance.cc:87] Workers of grape-engine initialized.
I20230313 11:35:51.506167    71 /home/graphscope/GraphScope/analytical_engine/core/server/analytical_server.cc:43] Analytical server is listening on 0.0.0.0:56263
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.
  HNP daemon   : [[20434,0],0] on node coordinator-qcwcky-666bb5b459-d45rv
  Remote daemon: [[20434,0],1] on node gs-engine-qcwcky-0
This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
command terminated with exit code 137
```

**Comment by Qingnan1** [comment]
![image](https://user-images.githubusercontent.com/44082344/225560379-e2ec03d9-9f6a-4368-a77b-d6e45b08f7d5.png)
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.ABORTED
        details = "$Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for details. The traceback is: Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 413, in CreateAnalyticalInstance
    engine_config = self._operation_executor.get_analytical_engine_config()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 369, in get_analytical_engine_config
    response_head, _ = self.run_on_analytical_engine(dag_def, [], {})
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/monitor.py", line 193, in runOnAnalyticalEngineWarp
    res = func(instance, dag_def, dag_bodies, loader_op_bodies)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 169, in run_on_analytical_engine
    response_head, response_bodies = self.run_step(dag_def, dag_bodies)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 102, in run_step
    responses = self.analytical_grpc_stub.RunStep(requests)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 364, in analytical_grpc_stub
    self._analytical_grpc_stub = self._create_analytical_grpc_stub()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 355, in _create_analytical_grpc_stub
    raise RuntimeError(
RuntimeError: Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for details
"
        debug_error_string = "{"created":"@1678955478.266269246","description":"Error received from peer
ipv4:10.175.123.48:30675","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"$Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for details. The
traceback is: Traceback (most recent call last):\n  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 413, in CreateAnalyticalInstance\n
engine_config = self._operation_executor.get_analytical_engine_config()\n  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 369, in
get_analytical_engine_config\n    response_head, _ = self.run_on_analytical_engine(dag_def, [], {})\n  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/monitor.py", line
193, in runOnAnalyticalEngineWarp\n    res = func(instance, dag_def, dag_bodies, loader_op_bodies)\n  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py",
line 169, in run_on_analytical_engine\n    response_head, response_bodies = self.run_step(dag_def, dag_bodies)\n  File
"/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 102, in run_step\n    responses = self.analytical_grpc_stub.RunStep(requests)\n  File
"/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 364, in analytical_grpc_stub\n    self._analytical_grpc_stub = self._create_analytical_grpc_stub()\n
File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 355, in _create_analytical_grpc_stub\n    raise RuntimeError(\nRuntimeError: Failed to connect to
engine in 60s, deployment may failed. Please check coordinator log for details\n","grpc_status":10}"

**Comment by JackyYangPassion** [comment]
> ```
> session = graphscope.session(
>        k8s_coordinator_cpu=1,
>        k8s_coordinator_mem="1Gi",
>        k8s_vineyard_cpu=0.2,
>        k8s_vineyard_mem="1Gi",
>        vineyard_shared_mem="2Gi",
>        k8s_engine_cpu=0.2,
>        k8s_engine_mem="1Gi",
>        k8s_image_tag="0.20.0a20230306",
>        num_workers=2,
>        k8s_namespace='gstest008',
>        k8s_client_config={"config_file": '/usr/local/airflow/dags/k8s_config'})
> ```
> 
> gs-engine-qcwcky-0 error log
> 
> ```
> 2023-03-13 03:35:48,864 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 0 time
> 2023-03-13 03:35:48,866 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
> 10.244.1.178 gs-engine-qcwcky-0
> I20230313 11:35:51.482007    61 /home/graphscope/GraphScope/analytical_engine/core/grape_instance.cc:87] Workers of grape-engine initialized.
> I20230313 11:35:51.506167    71 /home/graphscope/GraphScope/analytical_engine/core/server/analytical_server.cc:43] Analytical server is listening on 0.0.0.0:56263
> --------------------------------------------------------------------------
> ORTE has lost communication with a remote daemon.
>   HNP daemon   : [[20434,0],0] on node coordinator-qcwcky-666bb5b459-d45rv
>   Remote daemon: [[20434,0],1] on node gs-engine-qcwcky-0
> This is usually due to either a failure of the TCP network
> connection to the node, or possibly an internal failure of
> the daemon itself. We cannot recover from this failure, and
> therefore will terminate the job.
> --------------------------------------------------------------------------
> command terminated with exit code 137
> ```

when update to 0.20.0
it's running success!

**Comment by sighingnow** [comment]
Closing as fixed. Thanks for the feedback!

**Comment by Qingnan1** [comment]
> > ```
> > session = graphscope.session(
> >        k8s_coordinator_cpu=1,
> >        k8s_coordinator_mem="1Gi",
> >        k8s_vineyard_cpu=0.2,
> >        k8s_vineyard_mem="1Gi",
> >        vineyard_shared_mem="2Gi",
> >        k8s_engine_cpu=0.2,
> >        k8s_engine_mem="1Gi",
> >        k8s_image_tag="0.20.0a20230306",
> >        num_workers=2,
> >        k8s_namespace='gstest008',
> >        k8s_client_config={"config_file": '/usr/local/airflow/dags/k8s_config'})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gs-engine-qcwcky-0 error log
> > ```
> > 2023-03-13 03:35:48,864 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 0 time
> > 2023-03-13 03:35:48,866 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
> > 10.244.1.178 gs-engine-qcwcky-0
> > I20230313 11:35:51.482007    61 /home/graphscope/GraphScope/analytical_engine/core/grape_instance.cc:87] Workers of grape-engine initialized.
> > I20230313 11:35:51.506167    71 /home/graphscope/GraphScope/analytical_engine/core/server/analytical_server.cc:43] Analytical server is listening on 0.0.0.0:56263
> > --------------------------------------------------------------------------
> > ORTE has lost communication with a remote daemon.
> >   HNP daemon   : [[20434,0],0] on node coordinator-qcwcky-666bb5b459-d45rv
> >   Remote daemon: [[20434,0],1] on node gs-engine-qcwcky-0
> > This is usually due to either a failure of the TCP network
> > connection to the node, or possibly an internal failure of
> > the daemon itself. We cannot recover from this failure, and
> > therefore will terminate the job.
> > --------------------------------------------------------------------------
> > command terminated with exit code 137
> > ```
> 
> when update to 0.20.0 it's running success!

请教下，你是怎么安装的k8s集群，以及k8s集群版本是多少呀，我这边graphscope 一直失败

**Comment by siyuan0322** [comment]
@Qingnan1 请问具体是什么错误呢？可以一起看一下。 coordinator pod 的log。客户端的log

**Comment by Qingnan1** [comment]
最新错误信息贴在了 2571issue上

在 2023-03-28 21:40:14，"Siyuan Zhang" ***@***.***> 写道：


@Qingnan1 请问具体是什么错误呢？可以一起看一下。 coordinator pod 的log。客户端的log
