### ISSUE TITLE
[BUG] GIE gremlin subgraph with edge property filter error

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#2503]
**Describe the bug**

**To Reproduce**
```
g.V().has('name',within('zhangsan')).as('a').in('0..3','link').has('ratio', gte('0.4')).has('ratio',lte('0.9')).with('RESULT_OPT', 'ALL_V').with('PATH_OPT', 'SIMPLE').dedup()

```
it's running successful

```
g.V().has('name',within('zhangsan')).as('a').in('0..3','link').or(__.has('ratio', gte('0.4')),__.has('ratio',lte('0.9'))).with('RESULT_OPT', 'ALL_V').with('PATH_OPT', 'SIMPLE').dedup()

```
error
```
querySubgraph:  g.V().has('name',within('zhangsan')).as('a').in('0..3','link').or(__.has('ratio', gte('0.4')),__.has('ratio',lte('0.9'))).with('RESULT_OPT', 'ALL_V').with('PATH_OPT', 'SIMPLE').dedup()
2023-03-10 09:14:34,007 [INFO][op_executor:455]: execute gremlin query
2023-03-10 09:14:34,016 [INFO][op_executor:465]: put 5ed7dc48915c4919bf989b36caea6aab, client <gscoordinator.object_manager.InteractiveQueryManager object at 0x7f4abe567730>
2023-03-10 09:14:34,327 [ERROR][rpc:188]: Runstep failed with code: INTERACTIVE_ENGINE_INTERNAL_ERROR, message: Error occurred during RunStep, The traceback is: Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/gscoordinator/coordinator.py", line 315, in _RunStep
    head, bodies = self._operation_executor.run_on_interactive_engine(
  File "/root/anaconda3/lib/python3.9/site-packages/gscoordinator/monitor.py", line 210, in runOnInteractiveEngineWarp
    res = func(instance, dag_def)
  File "/root/anaconda3/lib/python3.9/site-packages/gscoordinator/op_executor.py", line 444, in run_on_interactive_engine
    op_result = self._fetch_gremlin_result(op)
  File "/root/anaconda3/lib/python3.9/site-packages/gscoordinator/op_executor.py", line 476, in _fetch_gremlin_result
    rlt = result_set.all().result()
  File "/root/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/root/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/root/anaconda3/lib/python3.9/site-packages/gremlin_python/driver/resultset.py", line 90, in cb
    f.result()
  File "/root/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/root/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/root/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/gremlin_python/driver/connection.py", line 83, in _receive
    status_code = self._protocol.data_received(data, self._results)
  File "/root/anaconda3/lib/python3.9/site-packages/gremlin_python/driver/protocol.py", line 138, in data_received
    raise GremlinServerError(message['status'])
gremlin_python.driver.protocol.GremlinServerError: 597: query [g.V().has('name',within('zhangsan')).as('a').in('0..3','link').or(__.has('ratio', gte('0.4')),__.has('ratio',lte('0.9'))).with('RESULT_OPT', 'ALL_V').with('PATH_OPT', 'SIMPLE').dedup()] is invalid, check the grammar in GremlinGS.g4, token: [@28,63:64='or',<49>,1:63].
```

**Environment (please complete the following information):**
 - GraphScope version: 0.19.0
 - OS: linux
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by shirly121** [comment]
The usage of `or(__.has('ratio', gte('0.4')),__.has('ratio',lte('0.9')))` has not been supported yet, but we extend `syntactic sugars` to support more flexible usages of expressions, which can be written like this:

g.V().has('name',within('zhangsan')).as('a').in('0..3','link').with('RESULT_OPT', 'ALL_V').with('PATH_OPT', 'SIMPLE').where(expr("@.ratio >= 0.4 || @.ratio <= 0.9")).dedup()

Another suggestion is `with('PATH_OPT', 'SIMPLE')` is the configurations of `path_expand` and should be followed by `in('0..3','link')`

**Comment by JackyYangPassion** [comment]
```
gremlin_python.driver.protocol.GremlinServerError: 500: Status{code=UNKNOWN, description=execution_error: user error: kind(Unknown), caused by:Unexpected data type in exec neither Vertex nor Edge entry is accessed in `Auxilia` operator, the entry is P(SimpleAllV([V(Vertex { id: 0, label: Some(0), details: Lazy(gs_store LazyVertexDetails { properties: None, inner: 0x7f2360009510 }) })])), cause=null}
```
