### ISSUE TITLE
[BUG] Analytical engine launching failed

### ISSUE THREAD

**Issue by Qingnan1** [alibaba/GraphScope#2571]
**Describe the bug**
graphscope cluster starts failed

**To Reproduce**
it is failing to run below command: 
sess = graphscope.session(num_workers=2)
**Expected behavior**
graphscope runs successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/44082344/228256584-426ebfdf-0845-4320-92bd-bcbe070c8948.png)
![image](https://user-images.githubusercontent.com/44082344/228257119-5b208041-e54b-44d3-879b-5b5b2ca1a4f7.png)

**error logs**
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.ABORTED
        details = "$Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for details. The traceback is: Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 413, in CreateAnalyticalInstance
    engine_config = self._operation_executor.get_analytical_engine_config()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 369, in get_analytical_engine_config
    response_head, _ = self.run_on_analytical_engine(dag_def, [], {})
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/monitor.py", line 193, in runOnAnalyticalEngineWarp
    res = func(instance, dag_def, dag_bodies, loader_op_bodies)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 169, in run_on_analytical_engine
    response_head, response_bodies = self.run_step(dag_def, dag_bodies)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 102, in run_step
    responses = self.analytical_grpc_stub.RunStep(requests)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 364, in analytical_grpc_stub
    self._analytical_grpc_stub = self._create_analytical_grpc_stub()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 355, in _create_analytical_grpc_stub
    raise RuntimeError(
RuntimeError: Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for details
"
        debug_error_string = "{"created":"@1680008010.548298283","description":"Error received from peer
ipv4:10.175.123.44:31525","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"$Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for
details. The traceback is: Traceback (most recent call last):\n  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 413, in
CreateAnalyticalInstance\n    engine_config = self._operation_executor.get_analytical_engine_config()\n  File
"/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 369, in get_analytical_engine_config\n    response_head, _ =
self.run_on_analytical_engine(dag_def, [], {})\n  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/monitor.py", line 193, in runOnAnalyticalEngineWarp\n
res = func(instance, dag_def, dag_bodies, loader_op_bodies)\n  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 169, in
run_on_analytical_engine\n    response_head, response_bodies = self.run_step(dag_def, dag_bodies)\n  File
"/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 102, in run_step\n    responses = self.analytical_grpc_stub.RunStep(requests)\n  File
"/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 364, in analytical_grpc_stub\n    self._analytical_grpc_stub =
self._create_analytical_grpc_stub()\n  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/gscoordinator/op_executor.py", line 355, in _create_analytical_grpc_stub\n    raise
RuntimeError(\nRuntimeError: Failed to connect to engine in 60s, deployment may failed. Please check coordinator log for details\n","grpc_status":10}"
```
```
error log from coordinator
2023-03-28 13:05:42,942 [INFO][kubernetes_launcher:591]: Starting GAE rpc service on 10.244.109.158:56426 ...
2023-03-28 13:05:44,016 [INFO][kubernetes_launcher:619]: Analytical engine launching command: /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-fobolb-0:1.0,gs-engine-fobolb-1:1.0 /opt/graphscope/bin/grape_engine --host 0.0.0.0 --port 56426 -v 1 --vineyard_socket /tmp/vineyard_workspace/vineyard.sock
2023-03-28 13:05:44,039 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 0 time
2023-03-28 13:05:44,039 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:05:47,107 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 1 time
2023-03-28 13:05:47,107 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:05:50,111 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 2 time
2023-03-28 13:05:50,112 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:05:53,116 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 3 time
2023-03-28 13:05:53,116 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:05:56,120 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 4 time
2023-03-28 13:05:56,120 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:05:59,124 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 5 time
2023-03-28 13:05:59,124 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:02,128 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 6 time
2023-03-28 13:06:02,128 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:05,208 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 7 time
2023-03-28 13:06:05,208 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:08,212 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 8 time
2023-03-28 13:06:08,212 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:11,217 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 9 time
2023-03-28 13:06:11,217 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:14,222 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 10 time
2023-03-28 13:06:14,222 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:17,226 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 11 time
2023-03-28 13:06:17,226 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:20,231 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 12 time
2023-03-28 13:06:20,231 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:23,307 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 13 time
2023-03-28 13:06:23,307 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:26,312 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 14 time
2023-03-28 13:06:26,312 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:29,317 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 15 time
2023-03-28 13:06:29,318 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:32,322 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 16 time
2023-03-28 13:06:32,323 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:35,327 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 17 time
2023-03-28 13:06:35,328 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:38,332 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 18 time
2023-03-28 13:06:38,333 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:41,408 [WARNING][op_executor:349]: Connecting to analytical engine... retrying 19 time
2023-03-28 13:06:41,409 [WARNING][op_executor:352]: Error code: StatusCode.UNAVAILABLE, details failed to connect to all addresses
2023-03-28 13:06:44,416 [INFO][coordinator:544]: Clean up resources, cleanup_instance: True, is_dangling: False
2023-03-28 13:06:44,416 [INFO][kubernetes_launcher:714]: Cleaning up kubernetes resources

```
```
run below command from pods getting error:
 kubectl exec  -n gs-vmgsyz  coordinator-lwywpd-6dc56d567d-tm85f -ti --  /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-lwywpd-0:1.0,gs-engine-lwywpd-1:1.0 /opt/graphscope/bin/grape_engine --host 0.0.0.0 --port 56774 -v 1 --vineyard_socket /tmp/vineyard_workspace/vineyard.sock
```
![image](https://user-images.githubusercontent.com/44082344/228259305-2c29b4c2-61bb-4087-bd9f-938ce6c9fc51.png)

**Environment (please complete the following information):**
 - GraphScope version:  0.20.0
 - OS: openeuler 
 - Version [20.03-LTS-SP3]
 - Kubernetes Version [1.25.5]

**Additional context**
build k8s cluster by kubeadm, following below steps
https://www.cnblogs.com/fenghua001/p/16849875.html

**Comment by siyuan0322** [comment]
> run below command from pods getting error:

It's because we set some environment variables when running the mpi. in [here](https://github.com/alibaba/GraphScope/blob/0b4f1e738b8520d7c398acebc05d53506f9f50fa/coordinator/gscoordinator/kubernetes_launcher.py#L660) and [here](https://github.com/alibaba/GraphScope/blob/0b4f1e738b8520d7c398acebc05d53506f9f50fa/coordinator/gscoordinator/utils.py#L1892)

Seems the mpi is not running, but I couldn't see any errors.
It's also could be that the coordinator cannot connect to the engine service.

Could you set the env `export OMPI_MCA_plm_rsh_agent=/usr/local/bin/kube_ssh` and rerun that mpirun command in coordinator pod?

**Comment by siyuan0322** [comment]
Running on openeuler is a new scenario for us, I'm interested in seeing if it works!

**Comment by Qingnan1** [comment]
I tried to run below commands:
```
 kubectl exec  -n  gs-ippmcw coordinator-hwyspf-5dd778df76-ql2vw -ti -- /bin/bash -c "export OMPI_MCA_plm_rsh_agent=/usr/local/bin/kube_ssh"
```
and then 
```
kubectl exec  -n gs-ippmcw coordinator-hwyspf-5dd778df76-ql2vw  -ti -- /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-hwyspf-0:1.0,gs-engine-hwyspf-1:1.0 /opt/graphscope/bin/grape_engine --host 0.0.0.0 --port 56496 -v 1 --vineyard_socket /tmp/vineyard_workspace/vineyard.sock
```
![image](https://user-images.githubusercontent.com/44082344/228464034-0f16bbda-b18a-4d8d-966e-24f423e9f142.png)
After that I tried below command:
```
kubectl exec  -n gs-ippmcw coordinator-hwyspf-5dd778df76-ql2vw  -ti -- /bin/bash -c "export OMPI_MCA_plm_rsh_agent=/usr/local/bin/kube_ssh" /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-hwyspf-0:1.0,gs-engine-hwyspf-1:1.0 /opt/graphscope/bin/grape_engine --host 0.0.0.0 --port 56496 -v 1 --vineyard_socket /tmp/vineyard_workspace/vineyard.sock
```
it returns nothing:
![image](https://user-images.githubusercontent.com/44082344/228464266-8f117633-5075-4a51-acf7-c746743b9f47.png)
How should I continue ?

**Comment by Qingnan1** [comment]
More information for you reference, I tried to debug to the pod , and then export below path
` export OMPI_MCA_plm_rsh_agent=/usr/local/bin/kube_ssh`
then I run below command in the container:
` /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-eqxyma-0:1.0,gs-engine-eqxyma-1:1.0 /opt/graphscope/bin/grape_engine --host 0.0.0.0 --port 56443 -v 1 --vineyard_socket /tmp/vineyard_workspace/vineyard.sock`
its running long time and seems like stuck their but no return until the k8s resource clean up by python client
![image](https://user-images.githubusercontent.com/44082344/228467656-c51f7d81-8420-4c71-85ad-ae122db0e266.png)

**Comment by siyuan0322** [comment]
I suspect that mpi cannot connect to workers.
Replace the `/opt/graphscope/bin/grape_engine -xxx ... vineyard.sock` to a simple command like `hostname`
Try this.
```
mpirun <xxx> hostname
```
And please paste your `ifconfig` output. Maybe we need to pick another network

**Comment by siyuan0322** [comment]
See if `bond0` or `eth0` is in the config.
And try add configurations and run again.
`mpirun -mca btl_tcp_if_include eth0` or `-mca btl_tcp_if_include bond0`

**Comment by siyuan0322** [comment]
Also you should check the firewall settings and if it is enabled (like it was for me), then try disabling it

**Comment by Qingnan1** [comment]
> Also you should check the firewall settings and if it is enabled (like it was for me), then try disabling it

![image](https://user-images.githubusercontent.com/44082344/228997012-928e96f2-5447-4129-abc3-6a416f6232ec.png)

**Comment by Qingnan1** [comment]
> 
From Ifconfig we don't have eth0 or bond0, how can we change the command to run mpi, I mean from python client

**Comment by Qingnan1** [comment]
BTW, I would like to know how does gs trigger mpirun? 
It is running  by k8s service ?

**Comment by Qingnan1** [comment]
> I suspect that mpi cannot connect to workers. Replace the `/opt/graphscope/bin/grape_engine -xxx ... vineyard.sock` to a simple command like `hostname` Try this.
> 
> ```
> mpirun <xxx> hostname
> ```

```
-- use hostname
[envbuilder@openeuler40 ~]$ kubectl exec  -n gs-bmjyaf coordinator-fegixv-75bf9ccd4c-q449z -ti -- /bin/bash
[graphscope@coordinator-fegixv-75bf9ccd4c-q449z ~]$ export OMPI_MCA_plm_rsh_agent=/usr/local/bin/kube_ssh
[graphscope@coordinator-fegixv-75bf9ccd4c-q449z ~]$ /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-fegixv-0:1.0,gs-engine-fegixv-1:1.0 hostname
command terminated with exit code 137
-- set mca btl_tcp_if_include eth0
[envbuilder@openeuler40 ~]$ kubectl exec  -n gs-jscjip coordinator-flfzwp-68464559d5-pmb69 -ti -- /bin/bash
[graphscope@coordinator-flfzwp-68464559d5-pmb69 ~]$ export OMPI_MCA_plm_rsh_agent=/usr/local/bin/kube_ssh
[graphscope@coordinator-flfzwp-68464559d5-pmb69 ~]$ /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-flfzwp-0:1.0,gs-engine-flfzwp-1:1.0 -mca btl_tcp_if_include eth0
--------------------------------------------------------------------------
No executable was specified on the mpirun command line.

Aborting.
--------------------------------------------------------------------------
-- set  mca btl_tcp_if_include and execute grape_engine, it is running until coordinator reach max retry times and clean up resource
[graphscope@coordinator-flfzwp-68464559d5-pmb69 ~]$ /opt/openmpi/bin/mpirun --allow-run-as-root --bind-to none -n 2 -host gs-engine-flfzwp-0:1.0,gs-engine-flfzwp-1:1.0 -mca btl_tcp_if_include eth0 /opt/graphscope/bin/grape_engine --host 0.0.0.0 --port 56690 -v 1 --vineyard_socket /tmp/vineyard_workspace/vineyard.sock
command terminated with exit code 137
```

**Comment by siyuan0322** [comment]
> From Ifconfig we don't have eth0 or bond0, but we have multiple NICs

Could you share your ifconfig?

> how can we change the command to run mpi（I mean from python client）

MPI command is not exposed to client. If we confirmed that it's could be resolve by configuring the command, I would submit a patch to enable it to be configured. Right now it's in [here](https://github.com/alibaba/GraphScope/blob/04d21ec27404ff668bbe89742816fb80038f5872/coordinator/gscoordinator/kubernetes_launcher.py#L659)

I suspect it's a compatible issue with openeuler. If you could share how you setup your cluster, I would like to get a ECS with openeuler and reproduce it. Is running minikube on openeuler is sufficient?

**Comment by siyuan0322** [comment]
> Sorry, we couldn't share the ifconfig as per company's limitations, we configured two network cards, one is for external network, another is for local network

I'm afraid that you have to tell mpi to use which ip interface.

> From Ifconfig we don't have eth0 or bond0, but we have multiple NICs ， how can we change the command to run mpi（I mean from python client）

Could you please find what ip interface on your machine, and include that interface in the `-mca btl_tcp_if_include eth0` (replace `eth0` to your ip interface accordingly)。 If there are multiple of them. We have to make sure the raw command succeed (the `mpirun xxx` by hand).

> I couldn't got some ECS with openeuler by some internal restrictions. So I'm afraid I couldn't reproduce your cluster setup 😢

**Comment by siyuan0322** [comment]
And this may help: https://www.open-mpi.org/faq/?category=tcp
I'm not an expert of MPI and not able to see the actual causes if I couldn't have the real scenarios and try myself 😂

**Comment by Qingnan1** [comment]
> > Sorry, we couldn't share the ifconfig as per company's limitations, we configured two network cards, one is for external network, another is for local network
> 
> I'm afraid that you have to tell mpi to use which ip interface.
> 
> > From Ifconfig we don't have eth0 or bond0, but we have multiple NICs ， how can we change the command to run mpi（I mean from python client）
> 
> Could you please find what ip interface on your machine, and include that interface in the `-mca btl_tcp_if_include eth0` (replace `eth0` to your ip interface accordingly)。 If there are multiple of them. We have to make sure the raw command succeed (the `mpirun xxx` by hand).
> 
> I couldn't get some ECS with openeuler by some internal restrictions. So I'm afraid I couldn't reproduce your cluster setup 😢

Thanks man, will try

**Comment by siyuan0322** [comment]
Feel free to reopen this if you have further problems or questions

**Comment by SuperBo** [comment]
Hi,
I have the same issue with GraphScope 0.24.0 on AWS EKS environment. Can't run mpi-run successfully on engine pods.
