### ISSUE TITLE
[BUG] result cannot decode dataframe with user define encoding

### ISSUE THREAD

**Issue by wuyueandrew** [alibaba/GraphScope#2606]
**Describe the bug**
context.to_dataframe throws exception , cuz encoding of dataframe is not utf-8

**To Reproduce**

**Expected behavior**

**Screenshots**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/framework/context.py", line 662, in to_dataframe
    return self._session._wrapper(
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/session.py", line 930, in _wrapper
    return self.run(dag_node)
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/session.py", line 952, in run
    return self.run_fetches(fetches)
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/session.py", line 974, in run_fetches
    return fetch_handler.wrap_results(response)
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/session.py", line 186, in wrap_results
    rets.append(decode_dataframe(op_result.result))
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/framework/utils.py", line 447, in decode_dataframe
    data_copy.append(archive.get_string())
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/archive.py", line 76, in get_string
    string = self.get_block(size).tobytes().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 3: invalid start byte

**Environment (please complete the following information):**

**Additional context**

**Comment by wuyueandrew** [comment]
maybe first decode with 'utf-8' and if throw a exception, abort decode use bytes

**Comment by wuyueandrew** [comment]
the latest impl, although ignore decode err, it return a wrong byte array
```
    def get_string(self):
        """Peek a string.
        Get string's length first (stored as a size_t), then get number of bytes
        equivalents to the length.
        """
        size = self.get_size()
        string = self.get_block(size).tobytes().decode("utf-8", errors="ignore")
        return string
```
