### ISSUE TITLE
[BUG] cannot run pagerank using code in tutorial 

### ISSUE THREAD

**Issue by ilovecomet** [alibaba/GraphScope#2608]
**Describe the bug**
when try to run pagerank using code below, reporting cmake warning and errors.

import graphscope
graphscope.set_option(show_log=False)
from graphscope.dataset import load_p2p_network
graph = load_p2p_network(directed=False)
simple_graph = graph.project(vertices={"host": []}, edges={"connect": ["dist"]})
from graphscope import pagerank
pr_context = pagerank(simple_graph, delta=0.85, max_round=10)

error:
2023-04-17 16:37:52,206 [ERROR][utils:276]: Failed to run command: cmake . -DNETWORKX=ON -DCMAKE_PREFIX_PATH='/usr/local/lib/python3.8/dist-packages/graphscope.runtime;/usr/local/lib/python3.8/dist-packages/graphscope.runtime/openmpi', error message is: CMake Error at CMakeLists.txt:228 (include):
  include could not find requested file:

    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake/FindGlog.cmake

CMake Error at CMakeLists.txt:237 (include):
  include could not find requested file:

    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake/FindArrow.cmake

CMake Error at CMakeLists.txt:248 (include):
  include could not find requested file:

    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake/FindLibUnwind.cmake

2023-04-17 16:37:52,244 [ERROR][rpc:188]: Runstep failed with code: ANALYTICAL_ENGINE_INTERNAL_ERROR, message: Error occurred during RunStep, The traceback is: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/utils.py", line 361, in _compile_on_local
    logger.debug(run_command(command, cwd=workdir))
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/utils.py", line 281, in run_command
    raise RuntimeError(f"Failed to run command: {args}, err: {err}")
RuntimeError: Failed to run command: cmake . -DNETWORKX=ON -DCMAKE_PREFIX_PATH='/usr/local/lib/python3.8/dist-packages/graphscope.runtime;/usr/local/lib/python3.8/dist-packages/graphscope.runtime/openmpi', err: CMake Error at CMakeLists.txt:228 (include):
  include could not find requested file:

    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake/FindGlog.cmake

CMake Error at CMakeLists.txt:237 (include):
  include could not find requested file:

    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake/FindArrow.cmake

CMake Error at CMakeLists.txt:248 (include):
  include could not find requested file:

    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake/FindLibUnwind.cmake

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/coordinator.py", line 309, in _RunStep
    head, bodies = self._operation_executor.run_on_analytical_engine(
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/monitor.py", line 193, in runOnAnalyticalEngineWarp
    res = func(instance, dag_def, dag_bodies, loader_op_bodies)
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/op_executor.py", line 167, in run_on_analytical_engine
    dag_def, dag_bodies = self.pre_process(dag_def, dag_bodies, loader_op_bodies)
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/op_executor.py", line 144, in pre_process
    op, _, _ = self._maybe_compile_app(op)
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/op_executor.py", line 257, in _maybe_compile_app
    compiled_path = self._compile_lib_and_distribute(
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/op_executor.py", line 395, in _compile_lib_and_distribute
    lib_path, java_jar_path, java_ffi_path, app_type = compile_func(
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/utils.py", line 540, in compile_app
    lib_path = compile_library(commands, library_dir, library_name, launcher)
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/utils.py", line 311, in compile_library
    return _compile_on_local(commands, workdir, output_name)
  File "/usr/local/lib/python3.8/dist-packages/gscoordinator/utils.py", line 368, in _compile_on_local
    raise CompilationError(
graphscope.framework.errors.CompilationError: Failed to compile 9f3574910dddeaf44ef30001376c0130c2ad531c99740d7326143ccbd344626a on platform system: Linux
machine: x86_64
platform: Linux-4.15.0-200-generic-x86_64-with-glibc2.27
uname: uname_result(system='Linux', node='c9c8c977cf55', release='4.15.0-200-generic', version='#211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022', machine='x86_64', processor='x86_64')
kernel_ver: #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022
mac_ver: ('', ('', '', ''), '')
gcc_ver: b'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0\nCopyright (C) 2017 Free Software Foundation, Inc.\nThis is free software; see the source for copying conditions.  There is NO\nwarranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n\n'
python_ver: 3.8.14

Traceback (most recent call last):
  File "/root/demo/code/graph_analysis.py", line 26, in <module>
    pr_context = pagerank(simple_graph,  delta=0.85, max_round=10)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/framework/app.py", line 76, in wrapper
    return func(projected, *args[1:], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/framework/app.py", line 139, in wrapper
    return not_compatible_for_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/analytical/app/pagerank.py", line 56, in pagerank
    return AppAssets(algo="pagerank", context="vertex_data")(graph, delta, max_round)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/framework/app.py", line 321, in __call__
    app_ = graph.session._wrapper(AppDAGNode(graph, self))
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/session.py", line 941, in _wrapper
    return self.run(dag_node)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/session.py", line 977, in run
    return self.run_fetches(fetches)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/session.py", line 987, in run_fetches
    response = self._grpc_client.run(fetch_handler.targets)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/rpc.py", line 98, in run
    return self._run_step_impl(dag_def)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/utils.py", line 156, in with_grpc_catch
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/graphscope/client/rpc.py", line 198, in _run_step_impl
    raise exc
graphscope.framework.errors.CompilationError: Failed to compile 9f3574910dddeaf44ef30001376c0130c2ad531c99740d7326143ccbd344626a on platform system: Linux
machine: x86_64
platform: Linux-4.15.0-200-generic-x86_64-with-glibc2.27
uname: uname_result(system='Linux', node='c9c8c977cf55', release='4.15.0-200-generic', version='#211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022', machine='x86_64', processor='x86_64')
kernel_ver: #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022
mac_ver: ('', ('', '', ''), '')
gcc_ver: b'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0\nCopyright (C) 2017 Free Software Foundation, Inc.\nThis is free software; see the source for copying conditions.  There is NO\nwarranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n\n'
python_ver: 3.8.14

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v 0.19.0]
 - OS: [e.g. Linux]

**Additional context**

**Comment by ilovecomet** [comment]
> Could you do `ls /usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake` and paste the output? And how did you installed graphscope?

I installed it using pip(pip install graphscope) and There is no such directory（/usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake）

**Comment by siyuan0322** [comment]
> > Could you do `ls /usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake` and paste the output? And how did you installed graphscope?
> 
> I installed it using pip(pip install graphscope) and There is no such directory（/usr/local/lib/python3.8/dist-packages/graphscope.runtime/cmake）

It could be a incomplete installation, some files are not downloaded. Could you try to install and upgrade `pip install graphscope -U` and find exactly which directory it was installed to in the pip logs.

**Comment by ilovecomet** [comment]
There is still no cmake directory available，but i find cmake directory  in the path(/usr/local/lib/python3.8/dist-packages/graphscope.runtime/lib/cmake/graphscope-analytical/cmake),then what should I do?

**Comment by siyuan0322** [comment]
Still the same error when compiling pagerank?

**Comment by ilovecomet** [comment]
yes, the same error

**Comment by siyuan0322** [comment]
Let me try to reproduce it. What's your environment? Ubuntu 20, 22 or centos

**Comment by ilovecomet** [comment]
Ubuntu 18.04.6 LTS

**Comment by siyuan0322** [comment]
<img width="449" alt="Screenshot 2023-04-19 at 14 52 26" src="https://user-images.githubusercontent.com/8400184/232990442-21ade9d7-8963-4304-9995-eb586181d18f.png">
Hi @ilovecomet I tried it on a 
 - ubuntu:18.04 docker image
 - installed cmake and build-essential from apt
 - installed python3.8 from deadsnaked ppa
 - install graphscope 0.19.0 from pip

And I couldn't reproduce it 😂 
I also tried 0.20.0 and it still works.

**Comment by siyuan0322** [comment]
And my cmake directory is same as yours, in `lib/python3.8/site-packages/graphscope.runtime/lib/cmake/graphscope-analytical/`

Is there any possibility that you have some directory that comes from older version of graphscope thus causes the error?

**Comment by siyuan0322** [comment]
Closed as stale. If you have any other questions, please feel free to reopen the issue.
