### ISSUE TITLE
[BUG] Pyarrow and Vineyard are not compatible versions.

### ISSUE THREAD

**Issue by wuyueandrew** [alibaba/GraphScope#2611]
**Describe the bug**
`ret.output("oss://xxx/result.parquet")`
And there is no write_batch api in pyarrow6.0.0.

**To Reproduce**

**Expected behavior**

**Screenshots**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/framework/context.py", line 687, in output
    return self._session._wrapper(
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/session.py", line 930, in _wrapper
    return self.run(dag_node)
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/session.py", line 952, in run
    return self.run_fetches(fetches)
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/session.py", line 962, in run_fetches
    response = self._grpc_client.run(fetch_handler.targets)
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/rpc.py", line 100, in run
    return self._run_step_impl(dag_def)
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/utils.py", line 156, in with_grpc_catch
    return fn(*args, **kwargs)
  File "/home/graphscope/.local/lib/python3.8/site-packages/graphscope/client/rpc.py", line 196, in _run_step_impl
    raise pickle.loads(response.full_exception)
RuntimeError: Unable to find a proper IO driver for oss://graph-dataset/miqi/simple_graph_3/ret/result.parquet, potential causes are:
 write_dataframe: Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.8/site-packages/vineyard/io/stream.py", line 106, in write
    writer(
  File "/home/graphscope/.local/lib/python3.8/site-packages/vineyard/drivers/io/stream.py", line 489, in write_dataframe
    write_parquet(
  File "/home/graphscope/.local/lib/python3.8/site-packages/vineyard/drivers/io/stream.py", line 462, in write_parquet
    launcher.join()
  File "/home/graphscope/.local/lib/python3.8/site-packages/vineyard/drivers/io/stream.py", line 143, in join
    raise RuntimeError(
RuntimeError: Subprocesses failed with the following error: 
Failed to launch job [/home/graphscope/.local/lib/python3.8/site-packages/vineyard/drivers/io/kube_ssh.sh datasimba:gs-engine-lshcfx-d6pzr vineyard_write_parquet /tmp/vineyard_workspace/vineyard.sock "oss://graph-dataset/miqi/simple_graph_3/ret/result.parquet" ...], exited with 1: 
Traceback (most recent call last):
  File "/home/graphscope/.local/bin/vineyard_write_parquet", line 8, in <module>
    sys.exit(main())
  File "/home/graphscope/.local/lib/python3.8/site-packages/vineyard/drivers/io/adaptors/write_parquet.py", line 105, in main
    write_parquet(
  File "/home/graphscope/.local/lib/python3.8/site-packages/vineyard/drivers/io/adaptors/write_parquet.py", line 83, in write_parquet
    writer.write_batch(batch)
AttributeError: 'ParquetWriter' object has no attribute 'write_batch'
Exception ignored in: <function ParquetWriter.__del__ at 0x7fd7b6a2c280>
Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.8/site-packages/pyarrow/parquet.py", line 680, in __del__
    self.close()
  File "/home/graphscope/.local/lib/python3.8/site-packages/pyarrow/parquet.py", line 705, in close
    self.writer.close()
  File "pyarrow/_parquet.pyx", line 1434, in pyarrow._parquet.ParquetWriter.close
  File "/home/graphscope/.local/lib/python3.8/site-packages/fsspec/spec.py", line 1565, in write
    raise ValueError("I/O operation on closed file.")
ValueError: I/O operation on closed file.
command terminated with exit code 1
**Environment (please complete the following information):**
 - GraphScope version: [0.19.0]

**Additional context**

**Comment by wuyueandrew** [comment]
my opinion is check `pa.__version__` first, if eq and gt 7.0.0 use  `write_batch` else use `write_table`

**Comment by wuyueandrew** [comment]
wrong way, i should copy it to vineyard
