### ISSUE TITLE
[BUG] GAE-Java jvm stackoverflow when running giraph apps.

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#2670]
StackOverflow when load graph via Giraph input format.

related pull request (emergency fix)https://github.com/alibaba/GraphScope/pull/2607/files
![C1ECC42E-04C8-4ADE-A166-3E57F8CA9C2C](https://user-images.githubusercontent.com/11537711/236412326-869205b1-8e30-4c9b-bee1-19880d83e30d.png)

**Comment by zhanglei1949** [comment]
2023-05-08 08:27:22
Full thread dump OpenJDK 64-Bit Server VM (11.0.18+10-post-Ubuntu-0ubuntu122.04 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fc52c13d3d0, length=10, elements={
0x0000564c5448f800, 0x0000564c54491800, 0x0000564c54497000, 0x0000564c54499000,
0x0000564c5449b000, 0x0000564c5449d000, 0x0000564c5449f000, 0x0000564c544e1000,
0x0000564c549b3000, 0x0000564c549b4800
}

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.13ms elapsed=42.75s tid=0x0000564c5448f800 nid=0x7019 waiting on condition  [0x00007fc562e69000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.18/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@11.0.18/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.18/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.22ms elapsed=42.74s tid=0x0000564c54491800 nid=0x701a in Object.wait()  [0x00007fc562d69000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.18/Native Method)
        - waiting on <0x00000001000024e8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.18/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x00000001000024e8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.18/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.18/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.07ms elapsed=42.74s tid=0x0000564c54497000 nid=0x701b runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=0 cpu=0.26ms elapsed=42.74s tid=0x0000564c54499000 nid=0x701c waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #6 daemon prio=9 os_prio=0 cpu=0.08ms elapsed=42.74s tid=0x0000564c5449b000 nid=0x701d runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=594.00ms elapsed=42.74s tid=0x0000564c5449d000 nid=0x701e waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=0 cpu=0.06ms elapsed=42.74s tid=0x0000564c5449f000 nid=0x701f runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #10 daemon prio=8 os_prio=0 cpu=0.17ms elapsed=42.73s tid=0x0000564c544e1000 nid=0x7021 in Object.wait()  [0x00007fc56237e000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.18/Native Method)
        - waiting on <0x000000010004dec8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.18/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x000000010004dec8> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@11.0.18/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)
        at jdk.internal.misc.InnocuousThread.run(java.base@11.0.18/InnocuousThread.java:161)

"pool-2-thread-1" #16 prio=5 os_prio=0 cpu=346.52ms elapsed=41.72s tid=0x0000564c549b3000 nid=0x7026 waiting on condition  [0x00007fc561b26000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.18/Native Method)
        - parking to wait for  <0x00000000fe7298f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.18/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.18/AbstractQueuedSynchronizer.java:2081)
        at java.util.concurrent.LinkedBlockingQueue.take(java.base@11.0.18/LinkedBlockingQueue.java:433)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.18/ThreadPoolExecutor.java:1054)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.18/ThreadPoolExecutor.java:1114)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.18/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)

"Thread-2" #17 prio=5 os_prio=0 cpu=1113.09ms elapsed=41.37s tid=0x0000564c549b4800 nid=0x6fef waiting on condition  [0x00007ffe9341f000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.18/Native Method)
        - parking to wait for  <0x00000000fec610e8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.18/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.18/AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.18/AbstractQueuedSynchronizer.java:917)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.18/AbstractQueuedSynchronizer.java:1240)
        at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.18/ReentrantLock.java:267)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(java.base@11.0.18/ThreadPoolExecutor.java:916)
        at java.util.concurrent.ThreadPoolExecutor.execute(java.base@11.0.18/ThreadPoolExecutor.java:1354)
        at java.lang.ProcessHandleImpl.completion(java.base@11.0.18/ProcessHandleImpl.java:135)
        at java.lang.ProcessImpl.initStreams(java.base@11.0.18/ProcessImpl.java:389)
        at java.lang.ProcessImpl.lambda$new$0(java.base@11.0.18/ProcessImpl.java:352)
        at java.lang.ProcessImpl$$Lambda$130/0x000000084019cc40.run(java.base@11.0.18/Unknown Source)
        at java.security.AccessController.doPrivileged(java.base@11.0.18/Native Method)
        at java.lang.ProcessImpl.<init>(java.base@11.0.18/ProcessImpl.java:351)
        at java.lang.ProcessImpl.start(java.base@11.0.18/ProcessImpl.java:271)
        at java.lang.ProcessBuilder.start(java.base@11.0.18/ProcessBuilder.java:1107)
        at java.lang.ProcessBuilder.start(java.base@11.0.18/ProcessBuilder.java:1071)
        at com.alibaba.graphscope.loader.LoaderUtils.getNumLinesOfFile(LoaderUtils.java:55)
        at com.alibaba.graphscope.loader.impl.FileLoader.loadEdgesImpl(FileLoader.java:286)
        at com.alibaba.graphscope.loader.impl.FileLoader.loadEdges(FileLoader.java:238)

"VM Thread" os_prio=0 cpu=2.53ms elapsed=42.75s tid=0x0000564c5448c800 nid=0x7018 runnable  

"GC Thread#0" os_prio=0 cpu=0.76ms elapsed=42.76s tid=0x0000564c5430d000 nid=0x7013 runnable  

"G1 Main Marker" os_prio=0 cpu=0.13ms elapsed=42.76s tid=0x0000564c54329800 nid=0x7014 runnable  

"G1 Conc#0" os_prio=0 cpu=0.05ms elapsed=42.76s tid=0x0000564c5432b800 nid=0x7015 runnable  

"G1 Refine#0" os_prio=0 cpu=0.11ms elapsed=42.76s tid=0x0000564c54456800 nid=0x7016 runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=3.66ms elapsed=42.75s tid=0x0000564c54458800 nid=0x7017 runnable  
"VM Periodic Task Thread" os_prio=0 cpu=12.27ms elapsed=42.73s tid=0x0000564c544df000 nid=0x7020 waiting on condition  

JNI global refs: 27, weak refs: 0
