### ISSUE TITLE
[BUG] CI (nondeterministically) failed with "err: error: unexpected EOF" during kubectl exec

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#2779]
**Describe the bug**

```
2023-05-30 12:02:03,750 [DEBUG][utils:357]: [ 50%] Building CXX object CMakeFiles/92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347.dir/opt/graphscope/include/graphscope/frame/app_frame.cc.o
[100%] Linking CXX shared library lib92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347.so
[100%] Built target 92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347
2023-05-30 12:02:03,750 [INFO][utils:285]: Running command: kubectl cp gs-engine-hytpdh-0:/tmp/gs/builtin/92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347/lib92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347.so /tmp/gs/builtin/92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347/lib92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347.so -c engine, cwd: None
Error: -30 12:02:13,994 [ERROR][utils:289]: Failed to run command: kubectl cp gs-engine-hytpdh-0:/tmp/gs/builtin/92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347/lib92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347.so /tmp/gs/builtin/92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347/lib92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347.so -c engine, error message is: error: unexpected EOF
Error: -30 12:02:13,997 [ERROR][rpc:188]: Runstep failed with code: ANALYTICAL_ENGINE_INTERNAL_ERROR, message: Error occurred during RunStep, The traceback is: Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/utils.py", line 359, in _compile_on_kubernetes
    logger.debug(run_command(cp))
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/utils.py", line 294, in run_command
    raise RuntimeError(f"Failed to run command: {args}, err: {err}")
RuntimeError: Failed to run command: kubectl cp gs-engine-hytpdh-0:/tmp/gs/builtin/92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347/lib92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347.so /tmp/gs/builtin/92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347/lib92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347.so -c engine, err: error: unexpected EOF


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/coordinator.py", line 311, in _RunStep
    head, bodies = self._operation_executor.run_on_analytical_engine(
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/monitor.py", line 193, in runOnAnalyticalEngineWarp
    res = func(instance, dag_def, dag_bodies, loader_op_bodies)
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/op_executor.py", line 168, in run_on_analytical_engine
    dag_def, dag_bodies = self.pre_process(dag_def, dag_bodies, loader_op_bodies)
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/op_executor.py", line 144, in pre_process
    op, _, _ = self._maybe_compile_app(op)
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/op_executor.py", line 258, in _maybe_compile_app
    compiled_path = self._compile_lib_and_distribute(
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/op_executor.py", line 398, in _compile_lib_and_distribute
    lib_path, java_jar_path, java_ffi_path, app_type = compile_func(
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/utils.py", line 562, in compile_app
    lib_path = compile_library(commands, library_dir, library_name, launcher)
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/utils.py", line 316, in compile_library
    return _compile_on_kubernetes(
  File "/home/graphscope/.local/lib/python3.10/site-packages/gscoordinator/utils.py", line 365, in _compile_on_kubernetes
    raise CompilationError(f"Failed to compile {output_name} on kubernetes") from e
graphscope.framework.errors.CompilationError: Failed to compile 92aeefe01533c144d7a0b6d325da7f0865f3dd82695c49b430ca6890d9bd3347 on kubernetes
```

See also:
- https://github.com/alibaba/GraphScope/actions/runs/5120647721/jobs/9207619638
- https://github.com/alibaba/GraphScope/actions/runs/5119468345/jobs/9204937247

**Comment by sighingnow** [comment]
Closing as resolved by https://github.com/alibaba/GraphScope/pull/2781
