### ISSUE TITLE
An error occurred when the hdfs saved the result of the graph algorithm

### ISSUE THREAD

**Issue by haohao0103** [alibaba/GraphScope#3484]
**Describe the bug**

**To Reproduce**
1. test code
```
def test_louvain_on_projected_grap_saveto_hdfs(arrow_property_graph_undirected):
    for v, e in itertools.product(["v0", "v1"], ["e0", "e1"]):
        g = arrow_property_graph_undirected.project(
            vertices={v: []}, edges={e: ["weight"]}
        )
        ctx = louvain(g)
        ## 测试写出数据到hdfs
        ctx.output(fd='hdfs://xxxx/lpa_result.csv',
    
                  selector={'node': 'v.id', 'result': 'r'},
    
                  host=' xxx.cn',
    
                  port=8020)
        res=ctx.to_dataframe({"node": "v.id", "r": "r"})
```

error message:
```
DEBUG:vineyard:command is: /home/graphscope/.local/lib/python3.10/site-packages/vineyard/drivers/io/ssh.sh localhost vineyard_write_bytes /tmp/vineyard.sock.1705399212.781564 "hdfs://hwyriskmgtcluster/user/alan578.zhao/lpa_result.csv" o00002853afaf35f4 eyJob3N0IjogImh3eS1objEtcmlza21ndC1oZHAtbm4tcHJkLTAyLm15aGxsLmNuIiwgInBvcnQiOiA4MDIwfQ== eyJob3N0IjogImh3eS1objEtcmlza21ndC1oZHAtbm4tcHJkLTAyLm15aGxsLmNuIiwgInBvcnQiOiA4MDIwfQ== 1 0
2024-01-16 10:07:07,377 [DEBUG][launcher:155]: driver: [error] Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.10/site-packages/vineyard/drivers/io/adaptors/write_bytes.py", line 76, in write_bytes
    of = fsspec.open(f"{path}_{proc_index}", "wb", **storage_options)
  File "/home/graphscope/.local/lib/python3.10/site-packages/fsspec/core.py", line 459, in open
    out = open_files(
  File "/home/graphscope/.local/lib/python3.10/site-packages/fsspec/core.py", line 283, in open_files
    fs, fs_token, paths = get_fs_token_paths(
  File "/home/graphscope/.local/lib/python3.10/site-packages/fsspec/core.py", line 623, in get_fs_token_paths
    chain = _un_chain(urlpath0, storage_options or {})
  File "/home/graphscope/.local/lib/python3.10/site-packages/fsspec/core.py", line 337, in _un_chain
    kw = dict(**extra_kwargs, **kws)
TypeError: dict() got multiple values for keyword argument 'host'
```

**Expected behavior**
It is hoped that the file can be saved to hdfs

**Screenshots**
![image](https://github.com/alibaba/GraphScope/assets/30570711/2933c081-9b5a-4518-bb09-294e778f9511)

**Environment (please complete the following information):**
 - GraphScope version: [0.25]
 - OS: [devcontainer ]

**Comment by siyuan0322** [comment]
Should use `fd='hdfs:///xxxx/lpa_result.csv'`.
3 `/`s

**Comment by haohao0103** [comment]
thanks
