### ISSUE TITLE
[BUG] Unexpected Results from Union Query in GIE

### ISSUE THREAD

**Issue by BingqingLyu** [alibaba/GraphScope#4385]
**Describe the bug**

Run the following Gremlin queries on the LDBC graph:

1. 
```
gremlin>  g.V().hasLabel("PERSON").has("id", 1816).union(outE("LIKES").limit(10).as('a').inV().as('b').select('a','b').by(elementMap()), outE("KNOWS").limit(10).as('c').inV().as('d').select('c','d').by(elementMap()))
java.lang.NullPointerException
Type ':help' or ':h' for help.
Display stack trace? [yN]
```
and the error in compiler is as follows:
```
java.lang.NullPointerException: null
        at com.alibaba.graphscope.common.exception.FrontendException.getMessage(FrontendException.java:68)
        at com.alibaba.graphscope.gremlin.resultx.GremlinResultProcessor.request(GremlinResultProcessor.java:112)
        at com.alibaba.graphscope.gremlin.plugin.processor.LifeCycleSupplier.lambda$get$2(LifeCycleSupplier.java:125)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:283)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

2.
```
gremlin>  g.V().hasLabel("PERSON").has("id", 1816).union(outE("LIKES").limit(10).as('a').inV().as('b').select('a','b').by(valueMap("creationDate")), outE("KNOWS").limit(10).as('c').inV().as('d').select('c','d').by(valueMap("creationDate")))
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
```

There appears to be a bug in the compiler's result parsing phase, as the backend returns the expected results but they are not being processed correctly.

**Comment by shirly121** [comment]
1. the query-1 can be written as 
```
g.V().hasLabel("PERSON").has("id", 1816).union(outE("LIKES").limit(10).as('a').inV().as('b').select('a','b').by(elementMap()), outE("KNOWS").limit(10).as('a').inV().as('b').select('a','b').by(elementMap()))
```
2. the bug of query-2 is fixed in #4404
