### ISSUE TITLE
[BUG] graphscope.framework.errors.AnalyticalEngineInternalError

### ISSUE THREAD

**Issue by maketubu7** [alibaba/GraphScope#46]
**Describe the bug**
An internal error occurred while I was loading the diagram

**Expected behavior**
`g = load_ogbn_mag(sess, "/home/bbduser/graphscope_test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/dataset/ogbn_mag.py", line 71, in load_ogbn_mag
    return sess.load_from(edges, vertices)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/session.py", line 649, in load_from
    return graphscope.load_from(*args, **kwargs)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/framework/graph_utils.py", line 615, in load_from
    graph_def = sess.run(op)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/session.py", line 531, in run
    response = self._grpc_client.run(dag)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/rpc.py", line 136, in run
    return self._run_step_impl(dag_def)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/rpc.py", line 45, in with_grpc_catch
    return fn(*args, **kwargs)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/rpc.py", line 223, in _run_step_impl
    return check_grpc_response(response)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/framework/errors.py", line 171, in check_grpc_response
    raise error_type(status.error_msg, detail)
graphscope.framework.errors.AnalyticalEngineInternalError: 'ArrowError occurred on worker 0: ArrowError occurred on worker 0: /usr/local/lib64/cmake/graphscope-analytical/../../../include/graphscope/core/loader/arrow_fragment_loader.h:368: readTableFromLocation -> IOError: Failed to open the /home/bbduser/graphscope_test/author_affiliated_with_institution.csv because: No such file or directory`
this file is exists

**Screenshots**
![image](https://user-images.githubusercontent.com/39480244/103117196-461fc480-46a4-11eb-957e-1cc0bc76e34b.png)

**Environment (please complete the following information):**
 - GraphScope version: GraphScope 0.1
 - OS:Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018
 - Version [e.g. 10.15]：python3.6.3
 - Kubernetes Version ：v1.20.1

**Additional context**

**Comment by lidongze0629** [comment]
GraphScope on kubernetes will mount ${GS_TEST_DIR} to /testingdata.

```shell
export GS_TEST_DIR=/home/bbduser/graphscope_test
g = load_ogbn_mag(sess, "/testingdata")
```

Note that make sure `path /home/bbduser/graphscope_test` exist on all node.

**Comment by maketubu7** [comment]
`os.environ["GS_TEST_DIR"] = os.path.expanduser("/home/bbduser/graphscope_test")
g = load_ogbn_mag(sess, "/testingdata")`

I export this variable but the error still exists
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/dataset/ogbn_mag.py", line 71, in load_ogbn_mag
    return sess.load_from(edges, vertices)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/session.py", line 649, in load_from
    return graphscope.load_from(*args, **kwargs)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/framework/graph_utils.py", line 615, in load_from
    graph_def = sess.run(op)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/session.py", line 531, in run
    response = self._grpc_client.run(dag)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/rpc.py", line 136, in run
    return self._run_step_impl(dag_def)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/rpc.py", line 45, in with_grpc_catch
    return fn(*args, **kwargs)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/client/rpc.py", line 223, in _run_step_impl
    return check_grpc_response(response)
  File "/home/bbduser/.local/lib/python3.7/site-packages/graphscope/framework/errors.py", line 171, in check_grpc_response
    raise error_type(status.error_msg, detail)
graphscope.framework.errors.AnalyticalEngineInternalError: 'ArrowError occurred on worker 0: ArrowError occurred on worker 0: /usr/local/lib64/cmake/graphscope-analytical/../../../include/graphscope/core/loader/arrow_fragment_loader.h:368: readTableFromLocation -> IOError: Failed to open the /testingdata/author_affiliated_with_institution.csv because: No such file or directory`

Did I do something wrong

**Comment by maketubu7** [comment]
> GraphScope on kubernetes will mount ${GS_TEST_DIR} to /testingdata.
> 
> ```shell
> export GS_TEST_DIR=/home/bbduser/graphscope_test
> g = load_ogbn_mag(sess, "/testingdata")
> ```
> 
> Note that make sure `path /home/bbduser/graphscope_test` exist on all node.

> os.environ["GS_TEST_DIR"] = os.path.expanduser("/home/bbduser/graphscope_test") 
> g = load_ogbn_mag(sess, "/testingdata")
I export this variable but the error still exists, Did I do something wrong

**Comment by lidongze0629** [comment]
> os.environ["GS_TEST_DIR"] = os.path.expanduser("/home/bbduser/graphscope_test")

After setting GS_TEST_DIR, should re-launch the session.
```shell
os.environ["GS_TEST_DIR"] = os.path.expanduser("/home/bbduser/graphscope_test")
sess = graphscope.session()
g = load_ogbn_mag(sess, "/testingdata")
```

**Comment by sighingnow** [comment]
Do we have a section about how to mount host/local volumes to pods?

**Comment by sighingnow** [comment]
Close as after #100 merged we have an option for users to mount external volumes into worker pods.
