### ISSUE TITLE
[BUG] Errors found in GraphScope standalone tryout

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphScope#948]
This is a summary of error or bug found by  GraphScope standalone tryout

**Comment by acezen** [comment]
- os: macos 10.15
- python version:  python3.9
- graphscope version: 0.8.0
- other context: installed vineyard
-  tryout code:
```python
import graphscope
import graphscope.nx as nx
G = nx.path_graph(10)
nx.builtin.pagerank(G)
```
- error log:
```bash
2021-11-04 15:05:35,159 [INFO][utils:308]: Codegened graph frame type: gs::DynamicProjectedFragment<grape::EmptyType,grape::EmptyType>
2021-11-04 15:05:35,161 [INFO][utils:347]: Building graph library ...
I20211104 15:05:59.000000 157962240 /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/grape_instance.cc:877] Registering Graph, graph type: DYNAMIC_PROJECTED, Type sigature: 92ecf016da9d4e246d47c268d41cf514c389b7ca7c02175f216b382ca0e4793f, lib path: /tmp/gs/builtin/92ecf016da9d4e246d47c268d41cf514c389b7ca7c02175f216b382ca0e4793f/lib92ecf016da9d4e246d47c268d41cf514c389b7ca7c02175f216b382ca0e4793f.dylib
==45584==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
"interceptors not installed" && 0*** Aborted at 1636009561 (unix time) try "date -d @1636009561" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x7fff726a033a) received by PID 45584 (TID 0x7000096a5000) stack trace: ***
    @     0x7fff727515fd _sigtramp
    @               0x66 (unknown)
    @     0x7fff72627808 abort
    @        0x111288cb6 __sanitizer::Abort()
    @        0x1112886a4 __sanitizer::Die()
    @        0x1112829ef __sanitizer::MaybeReexec()
    @        0x11127174e __asan::AsanInitInternal()
    @        0x1111361d3 (unknown)
    @        0x1111365de (unknown)
    @        0x111130ffb (unknown)
    @        0x111130f66 (unknown)
    @        0x111130f66 (unknown)
    @        0x11112f0b4 (unknown)
    @        0x11112f154 (unknown)
    @        0x111120ef2 (unknown)
    @        0x11112ae8f (unknown)
    @     0x7fff72543d8a dlopen
    @        0x1079b2a25 gs::open_lib()
    @        0x1079f0dda gs::GrapeInstance::registerGraphType()
    @        0x107968442 gs::GrapeInstance::OnReceive()
    @        0x107a06f75 gs::Dispatcher::processCmd()
    @        0x107a051e7 gs::Dispatcher::publisherLoop()
    @        0x107a05062 std::__1::__thread_proxy<>()
    @     0x7fff7275d109 _pthread_start
    @     0x7fff72758b8b thread_start
2021-11-04 15:06:01,730 [ERROR][coordinator:600]: Register graph failed, code: UNAVAILABLE, details: Socket closed
2021-11-04 15:06:01,730 [ERROR][coordinator:600]: Register graph failed, code: UNAVAILABLE, details: Socket closed
2021-11-04 15:06:01,731 [ERROR][rpc:55]: rpc _run_step_impl: failed with error code StatusCode.UNAVAILABLE, details: Socket closed
2021-11-04 15:06:02,039 [WARNING][coordinator:297]: Connect to analytical engine failed, engine may not started or closed. code: UNAVAILABLE, details: failed to connect to all addresses
2021-11-04 15:06:02,040 [WARNING][session:785]: 'RPC failed: rpc send_heartbeat failed: status <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.DEADLINE_EXCEEDED\n\tdetails = "Connect to analytical engine failed, engine may not started or closed. code: UNAVAILABLE, details: failed to connect to all addresses"\n\tdebug_error_string = "{"created":"@1636009562.040163000","description":"Error received from peer ipv6:[::1]:58235","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connect to analytical engine failed, engine may not started or closed. code: UNAVAILABLE, details: failed to connect to all addresses","grpc_status":4}"\n>'
2021-11-04 15:06:07,045 [ERROR][coordinator:1048]: Cleanup failed, code: UNAVAILABLE, details: failed to connect to all addresses
2021-11-04 15:06:07,045 [ERROR][coordinator:1048]: Cleanup failed, code: UNAVAILABLE, details: failed to connect to all addresses
I20211104 15:06:07.047525 155704768 vineyardd.cc:61] SIGTERM Signal received, stop vineyard server...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/graphscope/nx/algorithms/builtin.py", line 56, in wrapper
    graph = graph._project_to_simple()
  File "/usr/local/lib/python3.9/site-packages/graphscope/nx/classes/graph.py", line 2123, in _project_to_simple
    graph_def = op.eval(leaf=False)
  File "/usr/local/lib/python3.9/site-packages/graphscope/framework/operation.py", line 146, in eval
    res = sess.run(self)
  File "/usr/local/lib/python3.9/site-packages/graphscope/client/session.py", line 951, in run
    response = self._grpc_client.run(fetch_handler.targets)
  File "/usr/local/lib/python3.9/site-packages/graphscope/client/rpc.py", line 146, in run
    return self._run_step_impl(dag_def)
  File "/usr/local/lib/python3.9/site-packages/graphscope/client/rpc.py", line 59, in with_grpc_catch
    raise FatalError("The analytical engine server may down.") from None
graphscope.framework.errors.FatalError: 'The analytical engine server may down.'
```

**Comment by acezen** [comment]
- os: ubuntu20.04
- python version:  python3.8.10
- graphscope version: 0.8.0
- other context:  test on image ubuntu:20.04
-  tryout code:
```python
import graphscope
graphscope.set_option(show_log=True)
sess = graphscope.session(cluster_type="hosts", num_workers=1)
```
-- error log:
```bash
2021-11-04 07:26:46,227 [INFO][session:655]: Initializing graphscope session with parameters: {'addr': None, 'mode': 'eager', 'cluster_type': 'hosts', 'num_workers': 1, 'preemptive': True, 'k8s_namespace': None, 'k8s_service_type': 'NodePort', 'k8s_gs_image': 'registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.8.0', 'k8s_etcd_image': 'quay.io/coreos/etcd:v3.4.13', 'k8s_image_pull_policy': 'IfNotPresent', 'k8s_image_pull_secrets': [], 'k8s_coordinator_cpu': 1.5, 'k8s_coordinator_mem': '2Gi', 'k8s_etcd_num_pods': 1, 'k8s_etcd_cpu': 1.0, 'k8s_etcd_mem': '512Mi', 'k8s_vineyard_daemonset': 'none', 'k8s_vineyard_cpu': 0.2, 'k8s_vineyard_mem': '512Mi', 'vineyard_shared_mem': '4Gi', 'k8s_engine_cpu': 0.2, 'k8s_engine_mem': '1Gi', 'k8s_mars_worker_cpu': 0.2, 'k8s_mars_worker_mem': '512Mi', 'k8s_mars_scheduler_cpu': 0.2, 'k8s_mars_scheduler_mem': '512Mi', 'with_mars': False, 'enable_gaia': False, 'reconnect': False, 'k8s_volumes': {}, 'k8s_waiting_for_delete': False, 'timeout_seconds': 600, 'dangling_timeout_seconds': 600, 'hosts': ['localhost'], 'port': None, 'vineyard_socket': '', 'k8s_client_config': {}}
2021-11-04 07:26:46,227 [INFO][cluster:111]: Initializing coordinator with command: /usr/bin/python3 -m gscoordinator --num_workers 1 --hosts localhost --log_level INFO --timeout_seconds 600 --port 41200 --cluster_type hosts --instance_id dqiual --vineyard_shared_mem 4Gi --vineyard_socket
2021-11-04 07:26:46,235 [INFO][cluster:144]: Coordinator service started successful, connecting to service...
2021-11-04 07:26:47,245 [INFO][launcher:307]: Launch etcd with command: /usr/local/bin/etcd --data-dir /tmp/gs/dqiual --listen-peer-urls http://0.0.0.0:52040 --listen-client-urls http://0.0.0.0:40550 --advertise-client-urls http://127.0.0.1:40550 --initial-cluster default=http://127.0.0.1:52040 --initial-advertise-peer-urls http://127.0.0.1:52040
2021-11-04 07:26:47,252 [INFO][launcher:322]: Server is initializing etcd.
2021-11-04 07:26:48,254 [INFO][launcher:334]: Etcd is ready, endpoint is localhost:40550
2021-11-04 07:26:48,254 [INFO][launcher:409]: Launch vineyardd with command: /usr/bin/python3 -m vineyard --socket /tmp/vineyard.sock.1636010808.25438 --size 4Gi -etcd_endpoint http://localhost:40550 -etcd_prefix vineyard.gsa.1636010808.25438
2021-11-04 07:26:48,261 [INFO][launcher:424]: Server is initializing vineyardd.
I20211104 07:26:49.070436  5028 vineyardd.cc:91] Hello vineyard v0.3.4!
I20211104 07:26:49.070806  5028 meta_service.h:133] meta service is starting ...
I20211104 07:26:49.078943  5028 meta_service.h:140] start background etcd watch, since 1
I20211104 07:26:49.082613  5028 meta_service.h:399] Decide to set rank as 0
I20211104 07:26:49.082630  5028 meta_service.h:761] Instance join: 0
I20211104 07:26:49.083242  5028 meta_service.h:761] Instance join: 0
I20211104 07:26:49.083782  5028 ipc_server.cc:51] Vineyard will listen on "/tmp/vineyard.sock.1636010808.25438" for IPC
I20211104 07:26:49.083801  5028 rpc_server.cc:52] Vineyard will listen on 0.0.0.0:9600 for RPC
2021-11-04 07:26:49,262 [INFO][launcher:439]: Vineyardd is ready, ipc socket is /tmp/vineyard.sock.1636010808.25438
2021-11-04 07:26:49,269 [INFO][launcher:486]: Launch analytical engine with command: /usr/local/lib/python3.8/dist-packages/graphscope.runtime/bin/grape_engine --host 0.0.0.0 --port 33606 --vineyard_socket /tmp/vineyard.sock.1636010808.25438
2021-11-04 07:26:49,274 [INFO][launcher:501]: Server is initializing analytical engine.
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    agent-not-found
But I couldn't open the help file:
    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/share/openmpi/help-plm-rsh.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
[iZj6c2af7ajnkubfj612u2Z:05187] [[INVALID],INVALID] FORCE-TERMINATE AT Not found:-13 - error plm_rsh_component.c(335)
[iZj6c2af7ajnkubfj612u2Z:05184] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 716
[iZj6c2af7ajnkubfj612u2Z:05184] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 172
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/share/openmpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /usr/local/lib/python3.8/dist-packages/graphscope.runtime/share/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[iZj6c2af7ajnkubfj612u2Z:05184] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Comment by acezen** [comment]
- os: centos8
- python version: 3.6.8
- graphscope version: 0.8.0
- other context: test on image centos:8
- code
```bash
yum install python3-pip
pip install graphscope-0.8.0-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```
- error
```bash
[root@f8a72d2f9440 wheel]# pip3 install graphscope-0.8.0-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
graphscope-0.8.0-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

**Comment by acezen** [comment]
- os: centos8
- python version: 3.6.8
- graphscope version: 0.8.0
- other context: test on image centos:8
- code
```bash
yum install python3-pip
pip3 install --upgrade pip
pip3 install graphscope-0.8.0-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```
- error
```bash
[root@f8a72d2f9440 wheel]# pip3 install graphscope-0.8.0-py2.py3-none-Using legacy 'setup.py install' for daemons, since package 'wheel' is not installed.
Using legacy 'setup.py install' for hdfs3, since package 'wheel' is not installed.
Using legacy 'setup.py install' for oss2, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pickle5, since package 'wheel' is not installed.
Using legacy 'setup.py install' for treelib, since package 'wheel' is not installed.
Using legacy 'setup.py install' for aiobotocore, since package 'wheel' is not installed.
Using legacy 'setup.py install' for aliyun-python-sdk-core, since package 'wheel' is not installed.
Using legacy 'setup.py install' for crcmod, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Using legacy 'setup.py install' for idna-ssl, since package 'wheel' is not installed.
Installing collected packages: pycparser, typing-extensions, six, multidict, idna, cffi, zipp, yarl, urllib3, python-dateutil, jmespath, idna-ssl, cryptography, chardet, attrs, async-timeout, wrapt, pytz, pyasn1, numpy, importlib-resources, importlib-metadata, future, charset-normalizer, certifi, botocore, aliyun-python-sdk-core, aioitertools, aiohttp, treelib, sortedcontainers, shared-memory38, setuptools, rsa, requests, pycryptodome, pyasn1-modules, pyarrow, pickle5, pandas, oauthlib, fsspec, etcd-distro, crcmod, cachetools, backports.zoneinfo, argcomplete, aliyun-python-sdk-kms, aiobotocore, websocket-client, vineyard, s3fs, requests-oauthlib, PyYAML, pyparsing, pyorc, protobuf, oss2, nest-asyncio, isodate, hdfs3, grpcio, google-auth, decorator, aenum, vineyard-io, tqdm, scipy, packaging, networkx, kubernetes, grpcio-tools, gremlinpython, Cython, graphscope-client, daemons, cmake, graphscope
    Running setup.py install for idna-ssl ... done
    Running setup.py install for future ... done
    Running setup.py install for aliyun-python-sdk-core ... done
    Running setup.py install for treelib ... done
  Attempting uninstall: setuptools
    Found existing installation: setuptools 39.2.0
    Uninstalling setuptools-39.2.0:
      Successfully uninstalled setuptools-39.2.0
    Running setup.py install for pickle5 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3r34d4gs/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/pickle5
         cwd: /tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/
    Complete output (27 lines):
    running install
    /usr/local/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/pickle5
    copying pickle5/pickle.py -> build/lib.linux-x86_64-3.6/pickle5
    copying pickle5/__init__.py -> build/lib.linux-x86_64-3.6/pickle5
    copying pickle5/pickletools.py -> build/lib.linux-x86_64-3.6/pickle5
    creating build/lib.linux-x86_64-3.6/pickle5/test
    copying pickle5/test/pickletester.py -> build/lib.linux-x86_64-3.6/pickle5/test
    copying pickle5/test/test_pickle.py -> build/lib.linux-x86_64-3.6/pickle5/test
    copying pickle5/test/__init__.py -> build/lib.linux-x86_64-3.6/pickle5/test
    copying pickle5/test/test_picklebuffer.py -> build/lib.linux-x86_64-3.6/pickle5/test
    running build_ext
    building 'pickle5._pickle' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/pickle5
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c pickle5/_pickle.c -o build/temp.linux-x86_64-3.6/pickle5/_pickle.o -std=c99
    In file included from pickle5/_pickle.c:2:
    pickle5/compat.h:1:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3r34d4gs/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/pickle5 Check the logs for full command output.
```

**Comment by sighingnow** [comment]
> * os: centos8
> * python version: 3.6.8
> * graphscope version: 0.8.0
> * other context: test on image centos:8
> * code
> 
> ```shell
> yum install python3-pip
> pip3 install --upgrade pip
> pip3 install graphscope-0.8.0-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> ```
> 
> * error
> 
> ```shell
> [root@f8a72d2f9440 wheel]# pip3 install graphscope-0.8.0-py2.py3-none-Using legacy 'setup.py install' for daemons, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for hdfs3, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for oss2, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for pickle5, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for treelib, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for aiobotocore, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for aliyun-python-sdk-core, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for crcmod, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for idna-ssl, since package 'wheel' is not installed.
> Installing collected packages: pycparser, typing-extensions, six, multidict, idna, cffi, zipp, yarl, urllib3, python-dateutil, jmespath, idna-ssl, cryptography, chardet, attrs, async-timeout, wrapt, pytz, pyasn1, numpy, importlib-resources, importlib-metadata, future, charset-normalizer, certifi, botocore, aliyun-python-sdk-core, aioitertools, aiohttp, treelib, sortedcontainers, shared-memory38, setuptools, rsa, requests, pycryptodome, pyasn1-modules, pyarrow, pickle5, pandas, oauthlib, fsspec, etcd-distro, crcmod, cachetools, backports.zoneinfo, argcomplete, aliyun-python-sdk-kms, aiobotocore, websocket-client, vineyard, s3fs, requests-oauthlib, PyYAML, pyparsing, pyorc, protobuf, oss2, nest-asyncio, isodate, hdfs3, grpcio, google-auth, decorator, aenum, vineyard-io, tqdm, scipy, packaging, networkx, kubernetes, grpcio-tools, gremlinpython, Cython, graphscope-client, daemons, cmake, graphscope
>     Running setup.py install for idna-ssl ... done
>     Running setup.py install for future ... done
>     Running setup.py install for aliyun-python-sdk-core ... done
>     Running setup.py install for treelib ... done
>   Attempting uninstall: setuptools
>     Found existing installation: setuptools 39.2.0
>     Uninstalling setuptools-39.2.0:
>       Successfully uninstalled setuptools-39.2.0
>     Running setup.py install for pickle5 ... error
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3r34d4gs/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/pickle5
>          cwd: /tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/
>     Complete output (27 lines):
>     running install
>     /usr/local/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>       setuptools.SetuptoolsDeprecationWarning,
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-3.6
>     creating build/lib.linux-x86_64-3.6/pickle5
>     copying pickle5/pickle.py -> build/lib.linux-x86_64-3.6/pickle5
>     copying pickle5/__init__.py -> build/lib.linux-x86_64-3.6/pickle5
>     copying pickle5/pickletools.py -> build/lib.linux-x86_64-3.6/pickle5
>     creating build/lib.linux-x86_64-3.6/pickle5/test
>     copying pickle5/test/pickletester.py -> build/lib.linux-x86_64-3.6/pickle5/test
>     copying pickle5/test/test_pickle.py -> build/lib.linux-x86_64-3.6/pickle5/test
>     copying pickle5/test/__init__.py -> build/lib.linux-x86_64-3.6/pickle5/test
>     copying pickle5/test/test_picklebuffer.py -> build/lib.linux-x86_64-3.6/pickle5/test
>     running build_ext
>     building 'pickle5._pickle' extension
>     creating build/temp.linux-x86_64-3.6
>     creating build/temp.linux-x86_64-3.6/pickle5
>     gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c pickle5/_pickle.c -o build/temp.linux-x86_64-3.6/pickle5/_pickle.o -std=c99
>     In file included from pickle5/_pickle.c:2:
>     pickle5/compat.h:1:10: fatal error: Python.h: No such file or directory
>      #include "Python.h"
>               ^~~~~~~~~~
>     compilation terminated.
>     error: command 'gcc' failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pgbnievu/pickle5_2df380b7bbaa4846abaed00e6d781be3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3r34d4gs/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/pickle5 Check the logs for full command output.
> ```

This is because vineyard requires pickle5 for `python <= 3.7`, which further requires `python-devel` package been installed to compile the target.

The issue has been tracked at https://github.com/pitrou/pickle5-backport/issues/24
